'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace LightSwitchApplication

    #Region "Data Services"
    
    ''' <summary>
    ''' Provides members to query and update data in the ApplicationData datasource.
    ''' </summary>
    Public NotInheritable Partial Class ApplicationDataService
        Inherits Global.LightSwitchApplication.ApplicationData
    
        #Region "Constructors"
    
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New()
            MyBase.New()
        End Sub
    
        #End Region
    
        #Region "Private Properties"
        
        ''' <summary>
        ''' Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property Application As Global.LightSwitchApplication.Application
            Get
                Return Global.LightSwitchApplication.Application.Current
            End Get
        End Property
        
        ''' <summary>
        ''' Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property DataWorkspace As Global.LightSwitchApplication.DataWorkspace
            Get
                Return DirectCast(Me.Details.DataWorkspace, Global.LightSwitchApplication.DataWorkspace)
            End Get
        End Property
        
        #End Region
    
        #Region "Server Interceptions Points"
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Cleaners_CanInsert(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Cleaners_CanUpdate(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Cleaners_CanDelete(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Cleaners_CanRead(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Cleaners_Inserting(ByVal entity As Global.LightSwitchApplication.Cleaner)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Cleaners_Inserted(ByVal entity As Global.LightSwitchApplication.Cleaner)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Cleaners_Updating(ByVal entity As Global.LightSwitchApplication.Cleaner)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Cleaners_Updated(ByVal entity As Global.LightSwitchApplication.Cleaner)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Cleaners_Deleting(ByVal entity As Global.LightSwitchApplication.Cleaner)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Cleaners_Deleted(ByVal entity As Global.LightSwitchApplication.Cleaner)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Cleaners_Validate(ByVal entity As Global.LightSwitchApplication.Cleaner, ByVal results As Global.Microsoft.LightSwitch.EntitySetValidationResultsBuilder)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Clients_CanInsert(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Clients_CanUpdate(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Clients_CanDelete(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Clients_CanRead(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Clients_Inserting(ByVal entity As Global.LightSwitchApplication.Client)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Clients_Inserted(ByVal entity As Global.LightSwitchApplication.Client)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Clients_Updating(ByVal entity As Global.LightSwitchApplication.Client)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Clients_Updated(ByVal entity As Global.LightSwitchApplication.Client)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Clients_Deleting(ByVal entity As Global.LightSwitchApplication.Client)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Clients_Deleted(ByVal entity As Global.LightSwitchApplication.Client)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Clients_Validate(ByVal entity As Global.LightSwitchApplication.Client, ByVal results As Global.Microsoft.LightSwitch.EntitySetValidationResultsBuilder)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Jobs_CanInsert(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Jobs_CanUpdate(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Jobs_CanDelete(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Jobs_CanRead(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Jobs_Inserting(ByVal entity As Global.LightSwitchApplication.Job)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Jobs_Inserted(ByVal entity As Global.LightSwitchApplication.Job)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Jobs_Updating(ByVal entity As Global.LightSwitchApplication.Job)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Jobs_Updated(ByVal entity As Global.LightSwitchApplication.Job)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Jobs_Deleting(ByVal entity As Global.LightSwitchApplication.Job)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Jobs_Deleted(ByVal entity As Global.LightSwitchApplication.Job)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Jobs_Validate(ByVal entity As Global.LightSwitchApplication.Job, ByVal results As Global.Microsoft.LightSwitch.EntitySetValidationResultsBuilder)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub SaveChanges_CanExecute(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub SaveChanges_Executing()
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub SaveChanges_Executed()
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub SaveChanges_ExecuteFailed(ByVal exception As Global.System.Exception)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Cleaners_Single_CanExecute(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Cleaners_Single_Executing(ByVal Id As Global.System.Nullable(Of Integer))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Cleaners_Single_PreprocessQuery(ByVal Id As Global.System.Nullable(Of Integer), ByRef query As Global.System.Linq.IQueryable(Of Global.LightSwitchApplication.Cleaner))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Cleaners_Single_Executed(ByVal Id As Global.System.Nullable(Of Integer), ByVal result As Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.Cleaner))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Cleaners_Single_ExecuteFailed(ByVal Id As Global.System.Nullable(Of Integer), ByVal exception As Global.System.Exception)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Cleaners_SingleOrDefault_CanExecute(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Cleaners_SingleOrDefault_Executing(ByVal Id As Global.System.Nullable(Of Integer))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Cleaners_SingleOrDefault_PreprocessQuery(ByVal Id As Global.System.Nullable(Of Integer), ByRef query As Global.System.Linq.IQueryable(Of Global.LightSwitchApplication.Cleaner))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Cleaners_SingleOrDefault_Executed(ByVal Id As Global.System.Nullable(Of Integer), ByVal result As Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.Cleaner))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Cleaners_SingleOrDefault_ExecuteFailed(ByVal Id As Global.System.Nullable(Of Integer), ByVal exception As Global.System.Exception)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Cleaners_All_CanExecute(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Cleaners_All_Executing()
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Cleaners_All_PreprocessQuery(ByRef query As Global.System.Linq.IQueryable(Of Global.LightSwitchApplication.Cleaner))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Cleaners_All_Executed(ByVal result As Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.Cleaner))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Cleaners_All_ExecuteFailed(ByVal exception As Global.System.Exception)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Clients_Single_CanExecute(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Clients_Single_Executing(ByVal Id As Global.System.Nullable(Of Integer))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Clients_Single_PreprocessQuery(ByVal Id As Global.System.Nullable(Of Integer), ByRef query As Global.System.Linq.IQueryable(Of Global.LightSwitchApplication.Client))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Clients_Single_Executed(ByVal Id As Global.System.Nullable(Of Integer), ByVal result As Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.Client))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Clients_Single_ExecuteFailed(ByVal Id As Global.System.Nullable(Of Integer), ByVal exception As Global.System.Exception)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Clients_SingleOrDefault_CanExecute(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Clients_SingleOrDefault_Executing(ByVal Id As Global.System.Nullable(Of Integer))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Clients_SingleOrDefault_PreprocessQuery(ByVal Id As Global.System.Nullable(Of Integer), ByRef query As Global.System.Linq.IQueryable(Of Global.LightSwitchApplication.Client))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Clients_SingleOrDefault_Executed(ByVal Id As Global.System.Nullable(Of Integer), ByVal result As Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.Client))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Clients_SingleOrDefault_ExecuteFailed(ByVal Id As Global.System.Nullable(Of Integer), ByVal exception As Global.System.Exception)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Clients_All_CanExecute(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Clients_All_Executing()
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Clients_All_PreprocessQuery(ByRef query As Global.System.Linq.IQueryable(Of Global.LightSwitchApplication.Client))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Clients_All_Executed(ByVal result As Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.Client))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Clients_All_ExecuteFailed(ByVal exception As Global.System.Exception)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Jobs_Single_CanExecute(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Jobs_Single_Executing(ByVal Id As Global.System.Nullable(Of Integer))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Jobs_Single_PreprocessQuery(ByVal Id As Global.System.Nullable(Of Integer), ByRef query As Global.System.Linq.IQueryable(Of Global.LightSwitchApplication.Job))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Jobs_Single_Executed(ByVal Id As Global.System.Nullable(Of Integer), ByVal result As Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.Job))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Jobs_Single_ExecuteFailed(ByVal Id As Global.System.Nullable(Of Integer), ByVal exception As Global.System.Exception)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Jobs_SingleOrDefault_CanExecute(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Jobs_SingleOrDefault_Executing(ByVal Id As Global.System.Nullable(Of Integer))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Jobs_SingleOrDefault_PreprocessQuery(ByVal Id As Global.System.Nullable(Of Integer), ByRef query As Global.System.Linq.IQueryable(Of Global.LightSwitchApplication.Job))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Jobs_SingleOrDefault_Executed(ByVal Id As Global.System.Nullable(Of Integer), ByVal result As Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.Job))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Jobs_SingleOrDefault_ExecuteFailed(ByVal Id As Global.System.Nullable(Of Integer), ByVal exception As Global.System.Exception)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Jobs_All_CanExecute(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Jobs_All_Executing()
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Jobs_All_PreprocessQuery(ByRef query As Global.System.Linq.IQueryable(Of Global.LightSwitchApplication.Job))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Jobs_All_Executed(ByVal result As Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.Job))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Jobs_All_ExecuteFailed(ByVal exception As Global.System.Exception)
        End Sub
    
        #End Region
        
        #Region "Details Class"
    
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
        Public MustInherit Shadows Class DetailsClass
         
            Shared Sub New()
            End Sub
    
            Private Sub New()
            End Sub
            
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            Private Shared ReadOnly __CleanersEntry As Global.Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.Cleaner) = _
                New Global.Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.Cleaner)( _
                    "Cleaners",
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Cleaners_CanInsert, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Cleaners_CanUpdate, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Cleaners_CanDelete, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Cleaners_CanRead, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Cleaners_Inserting, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Cleaners_Inserted, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Cleaners_Updating, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Cleaners_Updated, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Cleaners_Deleting, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Cleaners_Deleted, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Cleaners_Validate)
            Private Shared Function __Cleaners_CanInsert(d As Global.LightSwitchApplication.ApplicationDataService) As Boolean
                Dim result As Boolean = True
                d.Cleaners_CanInsert(result)
                Return result
            End Function
            Private Shared Function __Cleaners_CanUpdate(d As Global.LightSwitchApplication.ApplicationDataService) As Boolean
                Dim result As Boolean = True
                d.Cleaners_CanUpdate(result)
                Return result
            End Function
            Private Shared Function __Cleaners_CanDelete(d As Global.LightSwitchApplication.ApplicationDataService) As Boolean
                Dim result As Boolean = True
                d.Cleaners_CanDelete(result)
                Return result
            End Function
            Private Shared Function __Cleaners_CanRead(d As Global.LightSwitchApplication.ApplicationDataService) As Boolean
                Dim result As Boolean = True
                d.Cleaners_CanRead(result)
                Return result
            End Function
            Private Shared Sub __Cleaners_Inserting(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Cleaner)
                d.Cleaners_Inserting(e)
            End Sub
            Private Shared Sub __Cleaners_Inserted(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Cleaner)
                d.Cleaners_Inserted(e)
            End Sub
            Private Shared Sub __Cleaners_Updating(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Cleaner)
                d.Cleaners_Updating(e)
            End Sub
            Private Shared Sub __Cleaners_Updated(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Cleaner)
                d.Cleaners_Updated(e)
            End Sub
            Private Shared Sub __Cleaners_Deleting(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Cleaner)
                d.Cleaners_Deleting(e)
            End Sub
            Private Shared Sub __Cleaners_Deleted(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Cleaner)
                d.Cleaners_Deleted(e)
            End Sub
            Private Shared Sub __Cleaners_Validate(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Cleaner, r As Global.Microsoft.LightSwitch.EntitySetValidationResultsBuilder)
                d.Cleaners_Validate(e, r)
            End Sub
            
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            Private Shared ReadOnly __ClientsEntry As Global.Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.Client) = _
                New Global.Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.Client)( _
                    "Clients",
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Clients_CanInsert, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Clients_CanUpdate, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Clients_CanDelete, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Clients_CanRead, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Clients_Inserting, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Clients_Inserted, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Clients_Updating, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Clients_Updated, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Clients_Deleting, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Clients_Deleted, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Clients_Validate)
            Private Shared Function __Clients_CanInsert(d As Global.LightSwitchApplication.ApplicationDataService) As Boolean
                Dim result As Boolean = True
                d.Clients_CanInsert(result)
                Return result
            End Function
            Private Shared Function __Clients_CanUpdate(d As Global.LightSwitchApplication.ApplicationDataService) As Boolean
                Dim result As Boolean = True
                d.Clients_CanUpdate(result)
                Return result
            End Function
            Private Shared Function __Clients_CanDelete(d As Global.LightSwitchApplication.ApplicationDataService) As Boolean
                Dim result As Boolean = True
                d.Clients_CanDelete(result)
                Return result
            End Function
            Private Shared Function __Clients_CanRead(d As Global.LightSwitchApplication.ApplicationDataService) As Boolean
                Dim result As Boolean = True
                d.Clients_CanRead(result)
                Return result
            End Function
            Private Shared Sub __Clients_Inserting(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Client)
                d.Clients_Inserting(e)
            End Sub
            Private Shared Sub __Clients_Inserted(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Client)
                d.Clients_Inserted(e)
            End Sub
            Private Shared Sub __Clients_Updating(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Client)
                d.Clients_Updating(e)
            End Sub
            Private Shared Sub __Clients_Updated(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Client)
                d.Clients_Updated(e)
            End Sub
            Private Shared Sub __Clients_Deleting(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Client)
                d.Clients_Deleting(e)
            End Sub
            Private Shared Sub __Clients_Deleted(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Client)
                d.Clients_Deleted(e)
            End Sub
            Private Shared Sub __Clients_Validate(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Client, r As Global.Microsoft.LightSwitch.EntitySetValidationResultsBuilder)
                d.Clients_Validate(e, r)
            End Sub
            
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            Private Shared ReadOnly __JobsEntry As Global.Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.Job) = _
                New Global.Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.Job)( _
                    "Jobs",
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Jobs_CanInsert, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Jobs_CanUpdate, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Jobs_CanDelete, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Jobs_CanRead, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Jobs_Inserting, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Jobs_Inserted, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Jobs_Updating, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Jobs_Updated, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Jobs_Deleting, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Jobs_Deleted, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Jobs_Validate)
            Private Shared Function __Jobs_CanInsert(d As Global.LightSwitchApplication.ApplicationDataService) As Boolean
                Dim result As Boolean = True
                d.Jobs_CanInsert(result)
                Return result
            End Function
            Private Shared Function __Jobs_CanUpdate(d As Global.LightSwitchApplication.ApplicationDataService) As Boolean
                Dim result As Boolean = True
                d.Jobs_CanUpdate(result)
                Return result
            End Function
            Private Shared Function __Jobs_CanDelete(d As Global.LightSwitchApplication.ApplicationDataService) As Boolean
                Dim result As Boolean = True
                d.Jobs_CanDelete(result)
                Return result
            End Function
            Private Shared Function __Jobs_CanRead(d As Global.LightSwitchApplication.ApplicationDataService) As Boolean
                Dim result As Boolean = True
                d.Jobs_CanRead(result)
                Return result
            End Function
            Private Shared Sub __Jobs_Inserting(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Job)
                d.Jobs_Inserting(e)
            End Sub
            Private Shared Sub __Jobs_Inserted(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Job)
                d.Jobs_Inserted(e)
            End Sub
            Private Shared Sub __Jobs_Updating(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Job)
                d.Jobs_Updating(e)
            End Sub
            Private Shared Sub __Jobs_Updated(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Job)
                d.Jobs_Updated(e)
            End Sub
            Private Shared Sub __Jobs_Deleting(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Job)
                d.Jobs_Deleting(e)
            End Sub
            Private Shared Sub __Jobs_Deleted(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Job)
                d.Jobs_Deleted(e)
            End Sub
            Private Shared Sub __Jobs_Validate(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Job, r As Global.Microsoft.LightSwitch.EntitySetValidationResultsBuilder)
                d.Jobs_Validate(e, r)
            End Sub
            
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            Private Shared ReadOnly __SaveChangesEntry As Global.Microsoft.LightSwitch.Details.Framework.Server.OperationEntry(Of Global.LightSwitchApplication.ApplicationDataService) = _
                New Global.Microsoft.LightSwitch.Details.Framework.Server.OperationEntry(Of Global.LightSwitchApplication.ApplicationDataService)( _
                    "SaveChanges",
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_CanExecute, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_Executing, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_Executed, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_Failed)
            Private Shared Function __SaveChanges_CanExecute(d As Global.LightSwitchApplication.ApplicationDataService, r As Boolean) As Boolean
                d.SaveChanges_CanExecute(r)
                Return r
            End Function
            Private Shared Sub __SaveChanges_Executing(d As Global.LightSwitchApplication.ApplicationDataService, args As Object())
                d.SaveChanges_Executing()
            End Sub
            Private Shared Sub __SaveChanges_Executed(d As Global.LightSwitchApplication.ApplicationDataService, args As Object())
                d.SaveChanges_Executed()
            End Sub
            Private Shared Sub __SaveChanges_Failed(d As Global.LightSwitchApplication.ApplicationDataService, args As Object(), ex As Global.System.Exception)
                d.SaveChanges_ExecuteFailed(ex)
            End Sub
            
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            Private Shared ReadOnly __Cleaners_SingleEntry As Global.Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.Cleaner) = _
                New Global.Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.Cleaner)( _
                    "Cleaners_Single",
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Cleaners_Single_CanExecute, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Cleaners_Single_Executing, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Cleaners_Single_Executed, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Cleaners_Single_Failed, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Cleaners_Single_PreprocessQuery)
            Private Shared Function __Cleaners_Single_CanExecute(d As Global.LightSwitchApplication.ApplicationDataService, r As Boolean) As Boolean
                d.Cleaners_Single_CanExecute(r)
                Return r
            End Function
            Private Shared Sub __Cleaners_Single_Executing(d As Global.LightSwitchApplication.ApplicationDataService, args As Object())
                d.Cleaners_Single_Executing(DirectCast(args(0), Global.System.Nullable(Of Integer)))
            End Sub
            Private Shared Sub __Cleaners_Single_Executed(d As Global.LightSwitchApplication.ApplicationDataService, args As Object())
                d.Cleaners_Single_Executed(DirectCast(args(0), Global.System.Nullable(Of Integer)), DirectCast(args(1), Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.Cleaner)))
            End Sub
            Private Shared Sub __Cleaners_Single_Failed(d As Global.LightSwitchApplication.ApplicationDataService, args As Object(), ex As Global.System.Exception)
                d.Cleaners_Single_ExecuteFailed(DirectCast(args(0), Global.System.Nullable(Of Integer)), ex)
            End Sub
            Private Shared Function __Cleaners_Single_PreprocessQuery(d As Global.LightSwitchApplication.ApplicationDataService, args As Object()) As Global.System.Linq.IQueryable
                Dim query As Global.System.Linq.IQueryable(Of Global.LightSwitchApplication.Cleaner) = DirectCast(args(1), Global.System.Linq.IQueryable(Of Global.LightSwitchApplication.Cleaner))
                d.Cleaners_Single_PreprocessQuery(DirectCast(args(0), Global.System.Nullable(Of Integer)), query)
                Return query
            End Function
            
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            Private Shared ReadOnly __Cleaners_SingleOrDefaultEntry As Global.Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.Cleaner) = _
                New Global.Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.Cleaner)( _
                    "Cleaners_SingleOrDefault",
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Cleaners_SingleOrDefault_CanExecute, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Cleaners_SingleOrDefault_Executing, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Cleaners_SingleOrDefault_Executed, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Cleaners_SingleOrDefault_Failed, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Cleaners_SingleOrDefault_PreprocessQuery)
            Private Shared Function __Cleaners_SingleOrDefault_CanExecute(d As Global.LightSwitchApplication.ApplicationDataService, r As Boolean) As Boolean
                d.Cleaners_SingleOrDefault_CanExecute(r)
                Return r
            End Function
            Private Shared Sub __Cleaners_SingleOrDefault_Executing(d As Global.LightSwitchApplication.ApplicationDataService, args As Object())
                d.Cleaners_SingleOrDefault_Executing(DirectCast(args(0), Global.System.Nullable(Of Integer)))
            End Sub
            Private Shared Sub __Cleaners_SingleOrDefault_Executed(d As Global.LightSwitchApplication.ApplicationDataService, args As Object())
                d.Cleaners_SingleOrDefault_Executed(DirectCast(args(0), Global.System.Nullable(Of Integer)), DirectCast(args(1), Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.Cleaner)))
            End Sub
            Private Shared Sub __Cleaners_SingleOrDefault_Failed(d As Global.LightSwitchApplication.ApplicationDataService, args As Object(), ex As Global.System.Exception)
                d.Cleaners_SingleOrDefault_ExecuteFailed(DirectCast(args(0), Global.System.Nullable(Of Integer)), ex)
            End Sub
            Private Shared Function __Cleaners_SingleOrDefault_PreprocessQuery(d As Global.LightSwitchApplication.ApplicationDataService, args As Object()) As Global.System.Linq.IQueryable
                Dim query As Global.System.Linq.IQueryable(Of Global.LightSwitchApplication.Cleaner) = DirectCast(args(1), Global.System.Linq.IQueryable(Of Global.LightSwitchApplication.Cleaner))
                d.Cleaners_SingleOrDefault_PreprocessQuery(DirectCast(args(0), Global.System.Nullable(Of Integer)), query)
                Return query
            End Function
            
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            Private Shared ReadOnly __Cleaners_AllEntry As Global.Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.Cleaner) = _
                New Global.Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.Cleaner)( _
                    "Cleaners_All",
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Cleaners_All_CanExecute, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Cleaners_All_Executing, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Cleaners_All_Executed, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Cleaners_All_Failed, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Cleaners_All_PreprocessQuery)
            Private Shared Function __Cleaners_All_CanExecute(d As Global.LightSwitchApplication.ApplicationDataService, r As Boolean) As Boolean
                d.Cleaners_All_CanExecute(r)
                Return r
            End Function
            Private Shared Sub __Cleaners_All_Executing(d As Global.LightSwitchApplication.ApplicationDataService, args As Object())
                d.Cleaners_All_Executing()
            End Sub
            Private Shared Sub __Cleaners_All_Executed(d As Global.LightSwitchApplication.ApplicationDataService, args As Object())
                d.Cleaners_All_Executed(DirectCast(args(0), Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.Cleaner)))
            End Sub
            Private Shared Sub __Cleaners_All_Failed(d As Global.LightSwitchApplication.ApplicationDataService, args As Object(), ex As Global.System.Exception)
                d.Cleaners_All_ExecuteFailed(ex)
            End Sub
            Private Shared Function __Cleaners_All_PreprocessQuery(d As Global.LightSwitchApplication.ApplicationDataService, args As Object()) As Global.System.Linq.IQueryable
                Dim query As Global.System.Linq.IQueryable(Of Global.LightSwitchApplication.Cleaner) = DirectCast(args(0), Global.System.Linq.IQueryable(Of Global.LightSwitchApplication.Cleaner))
                d.Cleaners_All_PreprocessQuery(query)
                Return query
            End Function
            
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            Private Shared ReadOnly __Clients_SingleEntry As Global.Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.Client) = _
                New Global.Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.Client)( _
                    "Clients_Single",
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Clients_Single_CanExecute, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Clients_Single_Executing, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Clients_Single_Executed, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Clients_Single_Failed, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Clients_Single_PreprocessQuery)
            Private Shared Function __Clients_Single_CanExecute(d As Global.LightSwitchApplication.ApplicationDataService, r As Boolean) As Boolean
                d.Clients_Single_CanExecute(r)
                Return r
            End Function
            Private Shared Sub __Clients_Single_Executing(d As Global.LightSwitchApplication.ApplicationDataService, args As Object())
                d.Clients_Single_Executing(DirectCast(args(0), Global.System.Nullable(Of Integer)))
            End Sub
            Private Shared Sub __Clients_Single_Executed(d As Global.LightSwitchApplication.ApplicationDataService, args As Object())
                d.Clients_Single_Executed(DirectCast(args(0), Global.System.Nullable(Of Integer)), DirectCast(args(1), Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.Client)))
            End Sub
            Private Shared Sub __Clients_Single_Failed(d As Global.LightSwitchApplication.ApplicationDataService, args As Object(), ex As Global.System.Exception)
                d.Clients_Single_ExecuteFailed(DirectCast(args(0), Global.System.Nullable(Of Integer)), ex)
            End Sub
            Private Shared Function __Clients_Single_PreprocessQuery(d As Global.LightSwitchApplication.ApplicationDataService, args As Object()) As Global.System.Linq.IQueryable
                Dim query As Global.System.Linq.IQueryable(Of Global.LightSwitchApplication.Client) = DirectCast(args(1), Global.System.Linq.IQueryable(Of Global.LightSwitchApplication.Client))
                d.Clients_Single_PreprocessQuery(DirectCast(args(0), Global.System.Nullable(Of Integer)), query)
                Return query
            End Function
            
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            Private Shared ReadOnly __Clients_SingleOrDefaultEntry As Global.Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.Client) = _
                New Global.Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.Client)( _
                    "Clients_SingleOrDefault",
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Clients_SingleOrDefault_CanExecute, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Clients_SingleOrDefault_Executing, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Clients_SingleOrDefault_Executed, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Clients_SingleOrDefault_Failed, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Clients_SingleOrDefault_PreprocessQuery)
            Private Shared Function __Clients_SingleOrDefault_CanExecute(d As Global.LightSwitchApplication.ApplicationDataService, r As Boolean) As Boolean
                d.Clients_SingleOrDefault_CanExecute(r)
                Return r
            End Function
            Private Shared Sub __Clients_SingleOrDefault_Executing(d As Global.LightSwitchApplication.ApplicationDataService, args As Object())
                d.Clients_SingleOrDefault_Executing(DirectCast(args(0), Global.System.Nullable(Of Integer)))
            End Sub
            Private Shared Sub __Clients_SingleOrDefault_Executed(d As Global.LightSwitchApplication.ApplicationDataService, args As Object())
                d.Clients_SingleOrDefault_Executed(DirectCast(args(0), Global.System.Nullable(Of Integer)), DirectCast(args(1), Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.Client)))
            End Sub
            Private Shared Sub __Clients_SingleOrDefault_Failed(d As Global.LightSwitchApplication.ApplicationDataService, args As Object(), ex As Global.System.Exception)
                d.Clients_SingleOrDefault_ExecuteFailed(DirectCast(args(0), Global.System.Nullable(Of Integer)), ex)
            End Sub
            Private Shared Function __Clients_SingleOrDefault_PreprocessQuery(d As Global.LightSwitchApplication.ApplicationDataService, args As Object()) As Global.System.Linq.IQueryable
                Dim query As Global.System.Linq.IQueryable(Of Global.LightSwitchApplication.Client) = DirectCast(args(1), Global.System.Linq.IQueryable(Of Global.LightSwitchApplication.Client))
                d.Clients_SingleOrDefault_PreprocessQuery(DirectCast(args(0), Global.System.Nullable(Of Integer)), query)
                Return query
            End Function
            
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            Private Shared ReadOnly __Clients_AllEntry As Global.Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.Client) = _
                New Global.Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.Client)( _
                    "Clients_All",
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Clients_All_CanExecute, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Clients_All_Executing, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Clients_All_Executed, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Clients_All_Failed, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Clients_All_PreprocessQuery)
            Private Shared Function __Clients_All_CanExecute(d As Global.LightSwitchApplication.ApplicationDataService, r As Boolean) As Boolean
                d.Clients_All_CanExecute(r)
                Return r
            End Function
            Private Shared Sub __Clients_All_Executing(d As Global.LightSwitchApplication.ApplicationDataService, args As Object())
                d.Clients_All_Executing()
            End Sub
            Private Shared Sub __Clients_All_Executed(d As Global.LightSwitchApplication.ApplicationDataService, args As Object())
                d.Clients_All_Executed(DirectCast(args(0), Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.Client)))
            End Sub
            Private Shared Sub __Clients_All_Failed(d As Global.LightSwitchApplication.ApplicationDataService, args As Object(), ex As Global.System.Exception)
                d.Clients_All_ExecuteFailed(ex)
            End Sub
            Private Shared Function __Clients_All_PreprocessQuery(d As Global.LightSwitchApplication.ApplicationDataService, args As Object()) As Global.System.Linq.IQueryable
                Dim query As Global.System.Linq.IQueryable(Of Global.LightSwitchApplication.Client) = DirectCast(args(0), Global.System.Linq.IQueryable(Of Global.LightSwitchApplication.Client))
                d.Clients_All_PreprocessQuery(query)
                Return query
            End Function
            
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            Private Shared ReadOnly __Jobs_SingleEntry As Global.Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.Job) = _
                New Global.Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.Job)( _
                    "Jobs_Single",
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Jobs_Single_CanExecute, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Jobs_Single_Executing, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Jobs_Single_Executed, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Jobs_Single_Failed, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Jobs_Single_PreprocessQuery)
            Private Shared Function __Jobs_Single_CanExecute(d As Global.LightSwitchApplication.ApplicationDataService, r As Boolean) As Boolean
                d.Jobs_Single_CanExecute(r)
                Return r
            End Function
            Private Shared Sub __Jobs_Single_Executing(d As Global.LightSwitchApplication.ApplicationDataService, args As Object())
                d.Jobs_Single_Executing(DirectCast(args(0), Global.System.Nullable(Of Integer)))
            End Sub
            Private Shared Sub __Jobs_Single_Executed(d As Global.LightSwitchApplication.ApplicationDataService, args As Object())
                d.Jobs_Single_Executed(DirectCast(args(0), Global.System.Nullable(Of Integer)), DirectCast(args(1), Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.Job)))
            End Sub
            Private Shared Sub __Jobs_Single_Failed(d As Global.LightSwitchApplication.ApplicationDataService, args As Object(), ex As Global.System.Exception)
                d.Jobs_Single_ExecuteFailed(DirectCast(args(0), Global.System.Nullable(Of Integer)), ex)
            End Sub
            Private Shared Function __Jobs_Single_PreprocessQuery(d As Global.LightSwitchApplication.ApplicationDataService, args As Object()) As Global.System.Linq.IQueryable
                Dim query As Global.System.Linq.IQueryable(Of Global.LightSwitchApplication.Job) = DirectCast(args(1), Global.System.Linq.IQueryable(Of Global.LightSwitchApplication.Job))
                d.Jobs_Single_PreprocessQuery(DirectCast(args(0), Global.System.Nullable(Of Integer)), query)
                Return query
            End Function
            
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            Private Shared ReadOnly __Jobs_SingleOrDefaultEntry As Global.Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.Job) = _
                New Global.Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.Job)( _
                    "Jobs_SingleOrDefault",
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Jobs_SingleOrDefault_CanExecute, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Jobs_SingleOrDefault_Executing, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Jobs_SingleOrDefault_Executed, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Jobs_SingleOrDefault_Failed, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Jobs_SingleOrDefault_PreprocessQuery)
            Private Shared Function __Jobs_SingleOrDefault_CanExecute(d As Global.LightSwitchApplication.ApplicationDataService, r As Boolean) As Boolean
                d.Jobs_SingleOrDefault_CanExecute(r)
                Return r
            End Function
            Private Shared Sub __Jobs_SingleOrDefault_Executing(d As Global.LightSwitchApplication.ApplicationDataService, args As Object())
                d.Jobs_SingleOrDefault_Executing(DirectCast(args(0), Global.System.Nullable(Of Integer)))
            End Sub
            Private Shared Sub __Jobs_SingleOrDefault_Executed(d As Global.LightSwitchApplication.ApplicationDataService, args As Object())
                d.Jobs_SingleOrDefault_Executed(DirectCast(args(0), Global.System.Nullable(Of Integer)), DirectCast(args(1), Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.Job)))
            End Sub
            Private Shared Sub __Jobs_SingleOrDefault_Failed(d As Global.LightSwitchApplication.ApplicationDataService, args As Object(), ex As Global.System.Exception)
                d.Jobs_SingleOrDefault_ExecuteFailed(DirectCast(args(0), Global.System.Nullable(Of Integer)), ex)
            End Sub
            Private Shared Function __Jobs_SingleOrDefault_PreprocessQuery(d As Global.LightSwitchApplication.ApplicationDataService, args As Object()) As Global.System.Linq.IQueryable
                Dim query As Global.System.Linq.IQueryable(Of Global.LightSwitchApplication.Job) = DirectCast(args(1), Global.System.Linq.IQueryable(Of Global.LightSwitchApplication.Job))
                d.Jobs_SingleOrDefault_PreprocessQuery(DirectCast(args(0), Global.System.Nullable(Of Integer)), query)
                Return query
            End Function
            
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            Private Shared ReadOnly __Jobs_AllEntry As Global.Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.Job) = _
                New Global.Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.Job)( _
                    "Jobs_All",
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Jobs_All_CanExecute, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Jobs_All_Executing, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Jobs_All_Executed, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Jobs_All_Failed, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Jobs_All_PreprocessQuery)
            Private Shared Function __Jobs_All_CanExecute(d As Global.LightSwitchApplication.ApplicationDataService, r As Boolean) As Boolean
                d.Jobs_All_CanExecute(r)
                Return r
            End Function
            Private Shared Sub __Jobs_All_Executing(d As Global.LightSwitchApplication.ApplicationDataService, args As Object())
                d.Jobs_All_Executing()
            End Sub
            Private Shared Sub __Jobs_All_Executed(d As Global.LightSwitchApplication.ApplicationDataService, args As Object())
                d.Jobs_All_Executed(DirectCast(args(0), Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.Job)))
            End Sub
            Private Shared Sub __Jobs_All_Failed(d As Global.LightSwitchApplication.ApplicationDataService, args As Object(), ex As Global.System.Exception)
                d.Jobs_All_ExecuteFailed(ex)
            End Sub
            Private Shared Function __Jobs_All_PreprocessQuery(d As Global.LightSwitchApplication.ApplicationDataService, args As Object()) As Global.System.Linq.IQueryable
                Dim query As Global.System.Linq.IQueryable(Of Global.LightSwitchApplication.Job) = DirectCast(args(0), Global.System.Linq.IQueryable(Of Global.LightSwitchApplication.Job))
                d.Jobs_All_PreprocessQuery(query)
                Return query
            End Function
    
        End Class
    
        #End Region
    
    End Class
    
    #End Region

End Namespace
