
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace LightSwitchApplication

    #Region "Data Workspace"
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public NotInheritable Class DataWorkspace
        Inherits Global.Microsoft.LightSwitch.Framework.Base.DataWorkspace(Of Global.LightSwitchApplication.DataWorkspace, Global.LightSwitchApplication.DataWorkspace.DetailsClass)
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Initializes a new instance of a DataWorkspace.  Changes can be made to data sources in the new instance independent of changes made to data sources in the default DataWorkspace.
        ''' </summary>
        Public Sub New()
            MyBase.New()
        End Sub
    
        #End Region
    
        #Region "Public Properties"
    
        ''' <summary>
        ''' Gets the ApplicationData datasource.  This provides members to query and update data in the data source.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property ApplicationData As Global.LightSwitchApplication.ApplicationData
            Get
                Return Global.LightSwitchApplication.DataWorkspace.DetailsClass.GetValue(Me, Global.LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.ApplicationData)
            End Get
        End Property
        
        #End Region
    
        #Region "Details Class"
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.DataWorkspaceDetails(Of Global.LightSwitchApplication.DataWorkspace, Global.LightSwitchApplication.DataWorkspace.DetailsClass, Global.LightSwitchApplication.DataWorkspace.DetailsClass.PropertySet)
    
            Shared Sub New()
                Dim initializeEntry = Global.LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.ApplicationData
            End Sub
    
            Public Sub New()
                MyBase.New()
            End Sub
    
            Public ReadOnly Shadows Property Properties As Global.LightSwitchApplication.DataWorkspace.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.DataWorkspacePropertySet(Of Global.LightSwitchApplication.DataWorkspace, Global.LightSwitchApplication.DataWorkspace.DetailsClass)
    
                Public Sub New()
                    MyBase.New()
                End Sub
    
                Public ReadOnly Property ApplicationData As Global.Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty(Of Global.LightSwitchApplication.DataWorkspace, Global.LightSwitchApplication.DataWorkspace.DetailsClass, Global.LightSwitchApplication.ApplicationData)
                    Get
                        Return TryCast(
                            MyBase.GetItem(Global.LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.ApplicationData),
                            Global.Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty(Of Global.LightSwitchApplication.DataWorkspace, Global.LightSwitchApplication.DataWorkspace.DetailsClass, Global.LightSwitchApplication.ApplicationData))
                    End Get
                End Property
                
            End Class
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend Class PropertySetProperties
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly ApplicationData As Global.Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty(Of Global.LightSwitchApplication.DataWorkspace, Global.LightSwitchApplication.DataWorkspace.DetailsClass, Global.LightSwitchApplication.ApplicationData).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty(Of Global.LightSwitchApplication.DataWorkspace, Global.LightSwitchApplication.DataWorkspace.DetailsClass, Global.LightSwitchApplication.ApplicationData).Entry( _
                        "ApplicationData", _
                        AddressOf Global.LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties._ApplicationData_Stub)
                Private Shared Sub _ApplicationData_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.DataWorkspace.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty(Of Global.LightSwitchApplication.DataWorkspace, Global.LightSwitchApplication.DataWorkspace.DetailsClass, Global.LightSwitchApplication.ApplicationData).Data), d As Global.LightSwitchApplication.DataWorkspace.DetailsClass, sf As Object)
                    c(d, d._ApplicationData, sf)
                End Sub
                 
            End Class
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _ApplicationData As Global.Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty(Of Global.LightSwitchApplication.DataWorkspace, Global.LightSwitchApplication.DataWorkspace.DetailsClass, Global.LightSwitchApplication.ApplicationData).Data
            
        End Class
    
        #End Region
    
    End Class
    
    #End Region
    
    #Region "Data Services"
    
    ''' <summary>
    ''' Provides members to query and update data in the ApplicationData datasource.
    ''' </summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public Class ApplicationData
        Inherits Global.Microsoft.LightSwitch.Framework.Base.DataService(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass)
    
        #Region "Constructors"
    
        Public Sub New()
            MyBase.New()
        End Sub
    
        #End Region
    
        #Region "Public Properties"
    
        ''' <summary>
        ''' Gets the Cleaners entity set.  The entity set provides members to access entities of a specific type.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property Cleaners As Global.Microsoft.LightSwitch.Framework.EntitySet(Of Global.LightSwitchApplication.Cleaner)
            Get
                Return Global.LightSwitchApplication.ApplicationData.DetailsClass.GetValue(Me, Global.LightSwitchApplication.ApplicationData.DetailsClass.PropertySetProperties.Cleaners)
            End Get
        End Property
        
        ''' <summary>
        ''' Gets the Clients entity set.  The entity set provides members to access entities of a specific type.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property Clients As Global.Microsoft.LightSwitch.Framework.EntitySet(Of Global.LightSwitchApplication.Client)
            Get
                Return Global.LightSwitchApplication.ApplicationData.DetailsClass.GetValue(Me, Global.LightSwitchApplication.ApplicationData.DetailsClass.PropertySetProperties.Clients)
            End Get
        End Property
        
        ''' <summary>
        ''' Gets the Jobs entity set.  The entity set provides members to access entities of a specific type.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property Jobs As Global.Microsoft.LightSwitch.Framework.EntitySet(Of Global.LightSwitchApplication.Job)
            Get
                Return Global.LightSwitchApplication.ApplicationData.DetailsClass.GetValue(Me, Global.LightSwitchApplication.ApplicationData.DetailsClass.PropertySetProperties.Jobs)
            End Get
        End Property
        
        #End Region
    
        #Region "Queries"
    
        ''' <summary>
        ''' Returns the entity whose identity is specified by the parameter(s).
        ''' </summary>
        ''' <param name="Id">
        ''' The value of the 'Id' key property of the entity to retrieve.
        ''' </param>
        Public Function Cleaners_Single(ByVal Id As Global.System.Nullable(Of Integer)) As Global.LightSwitchApplication.Cleaner
            Return Me.Details.Methods.Cleaners_Single.CreateInvocation(Id).Execute()
        End Function
        
        ''' <summary>
        ''' Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        ''' </summary>
        ''' <param name="Id">
        ''' The value of the 'Id' key property of the entity to retrieve.
        ''' </param>
        Public Function Cleaners_SingleOrDefault(ByVal Id As Global.System.Nullable(Of Integer)) As Global.LightSwitchApplication.Cleaner
            Return Me.Details.Methods.Cleaners_SingleOrDefault.CreateInvocation(Id).Execute()
        End Function
        
        ''' <summary>
        ''' Returns the entity whose identity is specified by the parameter(s).
        ''' </summary>
        ''' <param name="Id">
        ''' The value of the 'Id' key property of the entity to retrieve.
        ''' </param>
        Public Function Clients_Single(ByVal Id As Global.System.Nullable(Of Integer)) As Global.LightSwitchApplication.Client
            Return Me.Details.Methods.Clients_Single.CreateInvocation(Id).Execute()
        End Function
        
        ''' <summary>
        ''' Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        ''' </summary>
        ''' <param name="Id">
        ''' The value of the 'Id' key property of the entity to retrieve.
        ''' </param>
        Public Function Clients_SingleOrDefault(ByVal Id As Global.System.Nullable(Of Integer)) As Global.LightSwitchApplication.Client
            Return Me.Details.Methods.Clients_SingleOrDefault.CreateInvocation(Id).Execute()
        End Function
        
        ''' <summary>
        ''' Returns the entity whose identity is specified by the parameter(s).
        ''' </summary>
        ''' <param name="Id">
        ''' The value of the 'Id' key property of the entity to retrieve.
        ''' </param>
        Public Function Jobs_Single(ByVal Id As Global.System.Nullable(Of Integer)) As Global.LightSwitchApplication.Job
            Return Me.Details.Methods.Jobs_Single.CreateInvocation(Id).Execute()
        End Function
        
        ''' <summary>
        ''' Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        ''' </summary>
        ''' <param name="Id">
        ''' The value of the 'Id' key property of the entity to retrieve.
        ''' </param>
        Public Function Jobs_SingleOrDefault(ByVal Id As Global.System.Nullable(Of Integer)) As Global.LightSwitchApplication.Job
            Return Me.Details.Methods.Jobs_SingleOrDefault.CreateInvocation(Id).Execute()
        End Function
        
        #End Region
    
        #Region "Details Class"
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.DataServiceDetails(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.ApplicationData.DetailsClass.PropertySet, Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSet)
    
            Shared Sub New()
                Dim initializeMethodEntry = Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties.Cleaners_Single
                Dim initializePropertyEntry = Global.LightSwitchApplication.ApplicationData.DetailsClass.PropertySetProperties.Cleaners
            End Sub
    
            Public Sub New()
                MyBase.New()
            End Sub
    
            Public ReadOnly Shadows Property Methods As Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSet
                Get
                    Return MyBase.Methods
                End Get
            End Property
    
            Public ReadOnly Shadows Property Properties As Global.LightSwitchApplication.ApplicationData.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class MethodSet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.DataServiceMethodSet(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass)
    
                Public Sub New()
                    MyBase.New()
                End Sub
    
                Public ReadOnly Property Cleaners_Single As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Cleaner)
                    Get
                        Return TryCast(
                            MyBase.GetItem(Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties.Cleaners_Single),
                            Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Cleaner))
                    End Get
                End Property
                
                Public ReadOnly Property Cleaners_SingleOrDefault As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Cleaner)
                    Get
                        Return TryCast(
                            MyBase.GetItem(Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties.Cleaners_SingleOrDefault),
                            Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Cleaner))
                    End Get
                End Property
                
                Public ReadOnly Property Clients_Single As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Client)
                    Get
                        Return TryCast(
                            MyBase.GetItem(Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties.Clients_Single),
                            Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Client))
                    End Get
                End Property
                
                Public ReadOnly Property Clients_SingleOrDefault As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Client)
                    Get
                        Return TryCast(
                            MyBase.GetItem(Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties.Clients_SingleOrDefault),
                            Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Client))
                    End Get
                End Property
                
                Public ReadOnly Property Jobs_Single As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Job)
                    Get
                        Return TryCast(
                            MyBase.GetItem(Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties.Jobs_Single),
                            Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Job))
                    End Get
                End Property
                
                Public ReadOnly Property Jobs_SingleOrDefault As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Job)
                    Get
                        Return TryCast(
                            MyBase.GetItem(Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties.Jobs_SingleOrDefault),
                            Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Job))
                    End Get
                End Property
                
            End Class
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.DataServicePropertySet(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass)
    
                Public Sub New()
                    MyBase.New()
                End Sub
    
                Public ReadOnly Property Cleaners As Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Cleaner)
                    Get
                        Return TryCast(
                            MyBase.GetItem(Global.LightSwitchApplication.ApplicationData.DetailsClass.PropertySetProperties.Cleaners),
                            Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Cleaner))
                    End Get
                End Property
                
                Public ReadOnly Property Clients As Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Client)
                    Get
                        Return TryCast(
                            MyBase.GetItem(Global.LightSwitchApplication.ApplicationData.DetailsClass.PropertySetProperties.Clients),
                            Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Client))
                    End Get
                End Property
                
                Public ReadOnly Property Jobs As Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Job)
                    Get
                        Return TryCast(
                            MyBase.GetItem(Global.LightSwitchApplication.ApplicationData.DetailsClass.PropertySetProperties.Jobs),
                            Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Job))
                    End Get
                End Property
                
            End Class
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend Class MethodSetProperties
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Cleaners_Single As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Cleaner).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Cleaner).Entry( _
                        "Cleaners_Single", _
                        AddressOf Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties._Cleaners_Single_Stub)
                Private Shared Sub _Cleaners_Single_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Cleaner).Data), d As Global.LightSwitchApplication.ApplicationData.DetailsClass, sf As Object)
                    c(d, d._Cleaners_Single, sf)
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Cleaners_SingleOrDefault As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Cleaner).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Cleaner).Entry( _
                        "Cleaners_SingleOrDefault", _
                        AddressOf Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties._Cleaners_SingleOrDefault_Stub)
                Private Shared Sub _Cleaners_SingleOrDefault_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Cleaner).Data), d As Global.LightSwitchApplication.ApplicationData.DetailsClass, sf As Object)
                    c(d, d._Cleaners_SingleOrDefault, sf)
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Clients_Single As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Client).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Client).Entry( _
                        "Clients_Single", _
                        AddressOf Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties._Clients_Single_Stub)
                Private Shared Sub _Clients_Single_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Client).Data), d As Global.LightSwitchApplication.ApplicationData.DetailsClass, sf As Object)
                    c(d, d._Clients_Single, sf)
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Clients_SingleOrDefault As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Client).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Client).Entry( _
                        "Clients_SingleOrDefault", _
                        AddressOf Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties._Clients_SingleOrDefault_Stub)
                Private Shared Sub _Clients_SingleOrDefault_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Client).Data), d As Global.LightSwitchApplication.ApplicationData.DetailsClass, sf As Object)
                    c(d, d._Clients_SingleOrDefault, sf)
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Jobs_Single As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Job).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Job).Entry( _
                        "Jobs_Single", _
                        AddressOf Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties._Jobs_Single_Stub)
                Private Shared Sub _Jobs_Single_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Job).Data), d As Global.LightSwitchApplication.ApplicationData.DetailsClass, sf As Object)
                    c(d, d._Jobs_Single, sf)
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Jobs_SingleOrDefault As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Job).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Job).Entry( _
                        "Jobs_SingleOrDefault", _
                        AddressOf Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties._Jobs_SingleOrDefault_Stub)
                Private Shared Sub _Jobs_SingleOrDefault_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Job).Data), d As Global.LightSwitchApplication.ApplicationData.DetailsClass, sf As Object)
                    c(d, d._Jobs_SingleOrDefault, sf)
                End Sub
    
            End Class
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend Class PropertySetProperties
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Cleaners As Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Cleaner).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Cleaner).Entry( _
                        "Cleaners", _
                        AddressOf Global.LightSwitchApplication.ApplicationData.DetailsClass.PropertySetProperties._Cleaners_Stub)
                Private Shared Sub _Cleaners_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Cleaner).Data), d As Global.LightSwitchApplication.ApplicationData.DetailsClass, sf As Object)
                    c(d, d._Cleaners, sf)
                End Sub
     
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Clients As Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Client).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Client).Entry( _
                        "Clients", _
                        AddressOf Global.LightSwitchApplication.ApplicationData.DetailsClass.PropertySetProperties._Clients_Stub)
                Private Shared Sub _Clients_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Client).Data), d As Global.LightSwitchApplication.ApplicationData.DetailsClass, sf As Object)
                    c(d, d._Clients, sf)
                End Sub
     
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Jobs As Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Job).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Job).Entry( _
                        "Jobs", _
                        AddressOf Global.LightSwitchApplication.ApplicationData.DetailsClass.PropertySetProperties._Jobs_Stub)
                Private Shared Sub _Jobs_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Job).Data), d As Global.LightSwitchApplication.ApplicationData.DetailsClass, sf As Object)
                    c(d, d._Jobs, sf)
                End Sub
     
            End Class
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Cleaners As Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Cleaner).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Clients As Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Client).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Jobs As Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Job).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Cleaners_Single As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Cleaner).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Cleaners_SingleOrDefault As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Cleaner).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Clients_Single As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Client).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Clients_SingleOrDefault As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Client).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Jobs_Single As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Job).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Jobs_SingleOrDefault As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.Job).Data
            
        End Class
    
        #End Region
    
    End Class
    
    #End Region
    
End Namespace
