
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports __Job = LightSwitchApplication.Job

Namespace LightSwitchApplication

    #Region "Entities"
    
    ''' <summary>
    ''' No Modeled Description Available
    ''' </summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
    Public NotInheritable Partial Class Job
        Inherits Global.Microsoft.LightSwitch.Framework.Base.EntityObject(Of __Job, __Job.DetailsClass)
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Initializes a new instance of the Job entity.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New()
            Me.New(Nothing)
        End Sub
    
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New(entitySet As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __Job))
            MyBase.New(entitySet)
            
            __Job.DetailsClass.Initialize(Me)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Job_Created()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Job_AllowSaveWithErrors(ByRef result As Boolean)
        End Sub
    
        #End Region
    
        #Region "Private Properties"
        
        ''' <summary>
        ''' Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property Application As Global.Microsoft.LightSwitch.IApplication(Of Global.LightSwitchApplication.DataWorkspace)
            Get
                Return Global.LightSwitchApplication.Application.Current
            End Get
        End Property
        
        ''' <summary>
        ''' Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property DataWorkspace As Global.LightSwitchApplication.DataWorkspace
            Get
                Return DirectCast(Me.Details.EntitySet.Details.DataService.Details.DataWorkspace, Global.LightSwitchApplication.DataWorkspace)
            End Get
        End Property
        
        #End Region
    
        #Region "Public Properties"
    
        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Id As Integer
            Get
                Return __Job.DetailsClass.GetValue(Me, __Job.DetailsClass.PropertySetProperties.Id)
            End Get
            Set
                __Job.DetailsClass.SetValue(Me, __Job.DetailsClass.PropertySetProperties.Id, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Id_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Id_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Id_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property StartTime As Date
            Get
                Return __Job.DetailsClass.GetValue(Me, __Job.DetailsClass.PropertySetProperties.StartTime)
            End Get
            Set
                __Job.DetailsClass.SetValue(Me, __Job.DetailsClass.PropertySetProperties.StartTime, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub StartTime_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub StartTime_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub StartTime_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property EndTime As Date
            Get
                Return __Job.DetailsClass.GetValue(Me, __Job.DetailsClass.PropertySetProperties.EndTime)
            End Get
            Set
                __Job.DetailsClass.SetValue(Me, __Job.DetailsClass.PropertySetProperties.EndTime, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EndTime_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EndTime_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EndTime_Changed()
        End Sub

        ''' <summary>
        ''' Cost to Client
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Price As Decimal
            Get
                Return __Job.DetailsClass.GetValue(Me, __Job.DetailsClass.PropertySetProperties.Price)
            End Get
            Set
                __Job.DetailsClass.SetValue(Me, __Job.DetailsClass.PropertySetProperties.Price, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Price_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Price_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Price_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property CleanersRate As Decimal
            Get
                Return __Job.DetailsClass.GetValue(Me, __Job.DetailsClass.PropertySetProperties.CleanersRate)
            End Get
            Set
                __Job.DetailsClass.SetValue(Me, __Job.DetailsClass.PropertySetProperties.CleanersRate, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CleanersRate_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CleanersRate_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CleanersRate_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property PerPeriod As String
            Get
                Return __Job.DetailsClass.GetValue(Me, __Job.DetailsClass.PropertySetProperties.PerPeriod)
            End Get
            Set
                __Job.DetailsClass.SetValue(Me, __Job.DetailsClass.PropertySetProperties.PerPeriod, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub PerPeriod_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub PerPeriod_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub PerPeriod_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Recurance As String
            Get
                Return __Job.DetailsClass.GetValue(Me, __Job.DetailsClass.PropertySetProperties.Recurance)
            End Get
            Set
                __Job.DetailsClass.SetValue(Me, __Job.DetailsClass.PropertySetProperties.Recurance, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Recurance_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Recurance_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Recurance_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Note As String
            Get
                Return __Job.DetailsClass.GetValue(Me, __Job.DetailsClass.PropertySetProperties.Note)
            End Get
            Set
                __Job.DetailsClass.SetValue(Me, __Job.DetailsClass.PropertySetProperties.Note, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Note_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Note_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Note_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property QueryString As String
            Get
                Return __Job.DetailsClass.GetValue(Me, __Job.DetailsClass.PropertySetProperties.QueryString)
            End Get
            Set
                __Job.DetailsClass.SetValue(Me, __Job.DetailsClass.PropertySetProperties.QueryString, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub QueryString_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub QueryString_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub QueryString_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property IsDeleted As Boolean
            Get
                Return __Job.DetailsClass.GetValue(Me, __Job.DetailsClass.PropertySetProperties.IsDeleted)
            End Get
            Set
                __Job.DetailsClass.SetValue(Me, __Job.DetailsClass.PropertySetProperties.IsDeleted, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub IsDeleted_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub IsDeleted_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub IsDeleted_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Cleaner As Global.LightSwitchApplication.Cleaner
            Get
                Return __Job.DetailsClass.GetValue(Me, __Job.DetailsClass.PropertySetProperties.Cleaner)
            End Get
            Set
                __Job.DetailsClass.SetValue(Me, __Job.DetailsClass.PropertySetProperties.Cleaner, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Cleaner_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Cleaner_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Cleaner_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Client As Global.LightSwitchApplication.Client
            Get
                Return __Job.DetailsClass.GetValue(Me, __Job.DetailsClass.PropertySetProperties.Client)
            End Get
            Set
                __Job.DetailsClass.SetValue(Me, __Job.DetailsClass.PropertySetProperties.Client, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Client_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Client_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Client_Changed()
        End Sub

        #End Region
    
        #Region "Details Class"
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of _
                __Job, _
                __Job.DetailsClass, _
                __Job.DetailsClass.IImplementation, _
                __Job.DetailsClass.PropertySet, _
                Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __Job, __Job.DetailsClass), _
                Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __Job, __Job.DetailsClass))
    
            Shared Sub New()
                Dim initializeEntry = __Job.DetailsClass.PropertySetProperties.Id
            End Sub
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private Shared ReadOnly __JobEntry As Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __Job, __Job.DetailsClass).Entry = _
                New Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __Job, __Job.DetailsClass).Entry( _
                    AddressOf __Job.DetailsClass.__Job_CreateNew, _
                    AddressOf __Job.DetailsClass.__Job_Created, _
                    AddressOf __Job.DetailsClass.__Job_AllowSaveWithErrors)
            Private Shared Function __Job_CreateNew(es As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __Job)) As __Job
                Return New __Job(es)
            End Function
            Private Shared Sub __Job_Created(e As __Job)
                e.Job_Created()
            End Sub
            Private Shared Function __Job_AllowSaveWithErrors(e As __Job) As Boolean
                Dim result As Boolean = False
                e.Job_AllowSaveWithErrors(result)
                Return result
            End Function
    
            Public Sub New()
                MyBase.New()
            End Sub
    
            Public ReadOnly Shadows Property Commands As Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __Job, __Job.DetailsClass)
                Get
                    Return MyBase.Commands
                End Get
            End Property
    
            Public ReadOnly Shadows Property Methods As Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __Job, __Job.DetailsClass)
                Get
                    Return MyBase.Methods
                End Get
            End Property
    
            Public ReadOnly Shadows Property Properties As __Job.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet(Of __Job, __Job.DetailsClass)
    
                Public Sub New()
                    MyBase.New()
                End Sub
    
                Public ReadOnly Property Id As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, Integer)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Job.DetailsClass.PropertySetProperties.Id),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, Integer))
                    End Get
                End Property
                
                Public ReadOnly Property StartTime As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, Date)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Job.DetailsClass.PropertySetProperties.StartTime),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, Date))
                    End Get
                End Property
                
                Public ReadOnly Property EndTime As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, Date)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Job.DetailsClass.PropertySetProperties.EndTime),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, Date))
                    End Get
                End Property
                
                Public ReadOnly Property Price As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, Decimal)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Job.DetailsClass.PropertySetProperties.Price),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, Decimal))
                    End Get
                End Property
                
                Public ReadOnly Property CleanersRate As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, Decimal)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Job.DetailsClass.PropertySetProperties.CleanersRate),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, Decimal))
                    End Get
                End Property
                
                Public ReadOnly Property PerPeriod As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Job.DetailsClass.PropertySetProperties.PerPeriod),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Recurance As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Job.DetailsClass.PropertySetProperties.Recurance),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Note As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Job.DetailsClass.PropertySetProperties.Note),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property QueryString As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Job.DetailsClass.PropertySetProperties.QueryString),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property IsDeleted As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, Boolean)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Job.DetailsClass.PropertySetProperties.IsDeleted),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, Boolean))
                    End Get
                End Property
                
                Public ReadOnly Property Cleaner As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Job, __Job.DetailsClass, Global.LightSwitchApplication.Cleaner)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Job.DetailsClass.PropertySetProperties.Cleaner),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Job, __Job.DetailsClass, Global.LightSwitchApplication.Cleaner))
                    End Get
                End Property
                
                Public ReadOnly Property Client As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Job, __Job.DetailsClass, Global.LightSwitchApplication.Client)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Job.DetailsClass.PropertySetProperties.Client),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Job, __Job.DetailsClass, Global.LightSwitchApplication.Client))
                    End Get
                End Property
                
            End Class
    
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            Public Interface IImplementation
                Inherits Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
                Shadows Property Id As Integer
                Shadows Property StartTime As Date
                Shadows Property EndTime As Date
                Shadows Property Price As Decimal
                Shadows Property CleanersRate As Decimal
                Shadows Property PerPeriod As String
                Shadows Property Recurance As String
                Shadows Property Note As String
                Shadows Property QueryString As String
                Shadows Property IsDeleted As Boolean
                Shadows Property Cleaner As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
                Shadows Property Client As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
            End Interface
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend Class PropertySetProperties
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Id As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, Integer).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, Integer).Entry( _
                        "Id", _
                        AddressOf __Job.DetailsClass.PropertySetProperties._Id_Stub, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._Id_Validate, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._Id_GetImplementationValue, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._Id_SetImplementationValue, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._Id_OnValueChanged)
                Private Shared Sub _Id_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Job.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, Integer).Data), d As __Job.DetailsClass, sf As Object)
                    c(d, d._Id, sf)
                End Sub
                Private Shared Function _Id_ComputeIsReadOnly(e As __Job) As Boolean
                    Dim result As Boolean = False
                    e.Id_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Id_Validate(e As __Job, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Id_Validate(r)
                End Sub
                Private Shared Function _Id_GetImplementationValue(d As __Job.DetailsClass) As Integer
                    Return d.ImplementationEntity.Id
                End Function
                Private Shared Sub _Id_SetImplementationValue(d As __Job.DetailsClass, v As Integer)
                    d.ImplementationEntity.Id = v
                End Sub
                Private Shared Sub _Id_OnValueChanged(e As __Job)
                    e.Id_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly StartTime As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, Date).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, Date).Entry( _
                        "StartTime", _
                        AddressOf __Job.DetailsClass.PropertySetProperties._StartTime_Stub, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._StartTime_ComputeIsReadOnly, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._StartTime_Validate, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._StartTime_GetImplementationValue, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._StartTime_SetImplementationValue, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._StartTime_OnValueChanged)
                Private Shared Sub _StartTime_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Job.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, Date).Data), d As __Job.DetailsClass, sf As Object)
                    c(d, d._StartTime, sf)
                End Sub
                Private Shared Function _StartTime_ComputeIsReadOnly(e As __Job) As Boolean
                    Dim result As Boolean = False
                    e.StartTime_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _StartTime_Validate(e As __Job, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.StartTime_Validate(r)
                End Sub
                Private Shared Function _StartTime_GetImplementationValue(d As __Job.DetailsClass) As Date
                    Return d.ImplementationEntity.StartTime
                End Function
                Private Shared Sub _StartTime_SetImplementationValue(d As __Job.DetailsClass, v As Date)
                    d.ImplementationEntity.StartTime = __Job.DetailsClass.ClearDateTimeKind(v)
                End Sub
                Private Shared Sub _StartTime_OnValueChanged(e As __Job)
                    e.StartTime_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly EndTime As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, Date).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, Date).Entry( _
                        "EndTime", _
                        AddressOf __Job.DetailsClass.PropertySetProperties._EndTime_Stub, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._EndTime_ComputeIsReadOnly, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._EndTime_Validate, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._EndTime_GetImplementationValue, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._EndTime_SetImplementationValue, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._EndTime_OnValueChanged)
                Private Shared Sub _EndTime_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Job.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, Date).Data), d As __Job.DetailsClass, sf As Object)
                    c(d, d._EndTime, sf)
                End Sub
                Private Shared Function _EndTime_ComputeIsReadOnly(e As __Job) As Boolean
                    Dim result As Boolean = False
                    e.EndTime_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _EndTime_Validate(e As __Job, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.EndTime_Validate(r)
                End Sub
                Private Shared Function _EndTime_GetImplementationValue(d As __Job.DetailsClass) As Date
                    Return d.ImplementationEntity.EndTime
                End Function
                Private Shared Sub _EndTime_SetImplementationValue(d As __Job.DetailsClass, v As Date)
                    d.ImplementationEntity.EndTime = __Job.DetailsClass.ClearDateTimeKind(v)
                End Sub
                Private Shared Sub _EndTime_OnValueChanged(e As __Job)
                    e.EndTime_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Price As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, Decimal).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, Decimal).Entry( _
                        "Price", _
                        AddressOf __Job.DetailsClass.PropertySetProperties._Price_Stub, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._Price_ComputeIsReadOnly, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._Price_Validate, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._Price_GetImplementationValue, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._Price_SetImplementationValue, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._Price_OnValueChanged)
                Private Shared Sub _Price_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Job.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, Decimal).Data), d As __Job.DetailsClass, sf As Object)
                    c(d, d._Price, sf)
                End Sub
                Private Shared Function _Price_ComputeIsReadOnly(e As __Job) As Boolean
                    Dim result As Boolean = False
                    e.Price_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Price_Validate(e As __Job, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Price_Validate(r)
                End Sub
                Private Shared Function _Price_GetImplementationValue(d As __Job.DetailsClass) As Decimal
                    Return d.ImplementationEntity.Price
                End Function
                Private Shared Sub _Price_SetImplementationValue(d As __Job.DetailsClass, v As Decimal)
                    d.ImplementationEntity.Price = v
                End Sub
                Private Shared Sub _Price_OnValueChanged(e As __Job)
                    e.Price_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly CleanersRate As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, Decimal).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, Decimal).Entry( _
                        "CleanersRate", _
                        AddressOf __Job.DetailsClass.PropertySetProperties._CleanersRate_Stub, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._CleanersRate_ComputeIsReadOnly, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._CleanersRate_Validate, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._CleanersRate_GetImplementationValue, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._CleanersRate_SetImplementationValue, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._CleanersRate_OnValueChanged)
                Private Shared Sub _CleanersRate_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Job.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, Decimal).Data), d As __Job.DetailsClass, sf As Object)
                    c(d, d._CleanersRate, sf)
                End Sub
                Private Shared Function _CleanersRate_ComputeIsReadOnly(e As __Job) As Boolean
                    Dim result As Boolean = False
                    e.CleanersRate_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _CleanersRate_Validate(e As __Job, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.CleanersRate_Validate(r)
                End Sub
                Private Shared Function _CleanersRate_GetImplementationValue(d As __Job.DetailsClass) As Decimal
                    Return d.ImplementationEntity.CleanersRate
                End Function
                Private Shared Sub _CleanersRate_SetImplementationValue(d As __Job.DetailsClass, v As Decimal)
                    d.ImplementationEntity.CleanersRate = v
                End Sub
                Private Shared Sub _CleanersRate_OnValueChanged(e As __Job)
                    e.CleanersRate_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly PerPeriod As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, String).Entry( _
                        "PerPeriod", _
                        AddressOf __Job.DetailsClass.PropertySetProperties._PerPeriod_Stub, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._PerPeriod_ComputeIsReadOnly, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._PerPeriod_Validate, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._PerPeriod_GetImplementationValue, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._PerPeriod_SetImplementationValue, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._PerPeriod_OnValueChanged)
                Private Shared Sub _PerPeriod_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Job.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, String).Data), d As __Job.DetailsClass, sf As Object)
                    c(d, d._PerPeriod, sf)
                End Sub
                Private Shared Function _PerPeriod_ComputeIsReadOnly(e As __Job) As Boolean
                    Dim result As Boolean = False
                    e.PerPeriod_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _PerPeriod_Validate(e As __Job, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.PerPeriod_Validate(r)
                End Sub
                Private Shared Function _PerPeriod_GetImplementationValue(d As __Job.DetailsClass) As String
                    Return d.ImplementationEntity.PerPeriod
                End Function
                Private Shared Sub _PerPeriod_SetImplementationValue(d As __Job.DetailsClass, v As String)
                    d.ImplementationEntity.PerPeriod = v
                End Sub
                Private Shared Sub _PerPeriod_OnValueChanged(e As __Job)
                    e.PerPeriod_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Recurance As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, String).Entry( _
                        "Recurance", _
                        AddressOf __Job.DetailsClass.PropertySetProperties._Recurance_Stub, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._Recurance_ComputeIsReadOnly, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._Recurance_Validate, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._Recurance_GetImplementationValue, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._Recurance_SetImplementationValue, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._Recurance_OnValueChanged)
                Private Shared Sub _Recurance_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Job.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, String).Data), d As __Job.DetailsClass, sf As Object)
                    c(d, d._Recurance, sf)
                End Sub
                Private Shared Function _Recurance_ComputeIsReadOnly(e As __Job) As Boolean
                    Dim result As Boolean = False
                    e.Recurance_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Recurance_Validate(e As __Job, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Recurance_Validate(r)
                End Sub
                Private Shared Function _Recurance_GetImplementationValue(d As __Job.DetailsClass) As String
                    Return d.ImplementationEntity.Recurance
                End Function
                Private Shared Sub _Recurance_SetImplementationValue(d As __Job.DetailsClass, v As String)
                    d.ImplementationEntity.Recurance = v
                End Sub
                Private Shared Sub _Recurance_OnValueChanged(e As __Job)
                    e.Recurance_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Note As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, String).Entry( _
                        "Note", _
                        AddressOf __Job.DetailsClass.PropertySetProperties._Note_Stub, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._Note_ComputeIsReadOnly, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._Note_Validate, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._Note_GetImplementationValue, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._Note_SetImplementationValue, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._Note_OnValueChanged)
                Private Shared Sub _Note_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Job.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, String).Data), d As __Job.DetailsClass, sf As Object)
                    c(d, d._Note, sf)
                End Sub
                Private Shared Function _Note_ComputeIsReadOnly(e As __Job) As Boolean
                    Dim result As Boolean = False
                    e.Note_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Note_Validate(e As __Job, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Note_Validate(r)
                End Sub
                Private Shared Function _Note_GetImplementationValue(d As __Job.DetailsClass) As String
                    Return d.ImplementationEntity.Note
                End Function
                Private Shared Sub _Note_SetImplementationValue(d As __Job.DetailsClass, v As String)
                    d.ImplementationEntity.Note = v
                End Sub
                Private Shared Sub _Note_OnValueChanged(e As __Job)
                    e.Note_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly QueryString As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, String).Entry( _
                        "QueryString", _
                        AddressOf __Job.DetailsClass.PropertySetProperties._QueryString_Stub, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._QueryString_ComputeIsReadOnly, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._QueryString_Validate, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._QueryString_GetImplementationValue, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._QueryString_SetImplementationValue, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._QueryString_OnValueChanged)
                Private Shared Sub _QueryString_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Job.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, String).Data), d As __Job.DetailsClass, sf As Object)
                    c(d, d._QueryString, sf)
                End Sub
                Private Shared Function _QueryString_ComputeIsReadOnly(e As __Job) As Boolean
                    Dim result As Boolean = False
                    e.QueryString_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _QueryString_Validate(e As __Job, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.QueryString_Validate(r)
                End Sub
                Private Shared Function _QueryString_GetImplementationValue(d As __Job.DetailsClass) As String
                    Return d.ImplementationEntity.QueryString
                End Function
                Private Shared Sub _QueryString_SetImplementationValue(d As __Job.DetailsClass, v As String)
                    d.ImplementationEntity.QueryString = v
                End Sub
                Private Shared Sub _QueryString_OnValueChanged(e As __Job)
                    e.QueryString_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly IsDeleted As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, Boolean).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, Boolean).Entry( _
                        "IsDeleted", _
                        AddressOf __Job.DetailsClass.PropertySetProperties._IsDeleted_Stub, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._IsDeleted_ComputeIsReadOnly, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._IsDeleted_Validate, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._IsDeleted_GetImplementationValue, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._IsDeleted_SetImplementationValue, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._IsDeleted_OnValueChanged)
                Private Shared Sub _IsDeleted_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Job.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, Boolean).Data), d As __Job.DetailsClass, sf As Object)
                    c(d, d._IsDeleted, sf)
                End Sub
                Private Shared Function _IsDeleted_ComputeIsReadOnly(e As __Job) As Boolean
                    Dim result As Boolean = False
                    e.IsDeleted_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _IsDeleted_Validate(e As __Job, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.IsDeleted_Validate(r)
                End Sub
                Private Shared Function _IsDeleted_GetImplementationValue(d As __Job.DetailsClass) As Boolean
                    Return d.ImplementationEntity.IsDeleted
                End Function
                Private Shared Sub _IsDeleted_SetImplementationValue(d As __Job.DetailsClass, v As Boolean)
                    d.ImplementationEntity.IsDeleted = v
                End Sub
                Private Shared Sub _IsDeleted_OnValueChanged(e As __Job)
                    e.IsDeleted_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Cleaner As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Job, __Job.DetailsClass, Global.LightSwitchApplication.Cleaner).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Job, __Job.DetailsClass, Global.LightSwitchApplication.Cleaner).Entry( _
                        "Cleaner", _
                        AddressOf __Job.DetailsClass.PropertySetProperties._Cleaner_Stub, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._Cleaner_ComputeIsReadOnly, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._Cleaner_Validate, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._Cleaner_GetCoreImplementationValue, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._Cleaner_GetImplementationValue, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._Cleaner_SetImplementationValue, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._Cleaner_Refresh, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._Cleaner_OnValueChanged)
                Private Shared Sub _Cleaner_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Job.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Job, __Job.DetailsClass, Global.LightSwitchApplication.Cleaner).Data), d As __Job.DetailsClass, sf As Object)
                    c(d, d._Cleaner, sf)
                End Sub
                Private Shared Function _Cleaner_ComputeIsReadOnly(e As __Job) As Boolean
                    Dim result As Boolean = False
                    e.Cleaner_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Cleaner_Validate(e As __Job, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Cleaner_Validate(r)
                End Sub
                Private Shared Function _Cleaner_GetCoreImplementationValue(d as __Job.DetailsClass) As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
                    Return d.ImplementationEntity.Cleaner
                End Function
                Private Shared Function _Cleaner_GetImplementationValue(d as __Job.DetailsClass) As Global.LightSwitchApplication.Cleaner
                    Return d.GetImplementationValue(Of Global.LightSwitchApplication.Cleaner, Global.LightSwitchApplication.Cleaner.DetailsClass)(__Job.DetailsClass.PropertySetProperties.Cleaner, d._Cleaner)
                End Function
                Private Shared Sub _Cleaner_SetImplementationValue(d As __Job.DetailsClass, v As Global.LightSwitchApplication.Cleaner)
                    d.SetImplementationValue(__Job.DetailsClass.PropertySetProperties.Cleaner, d._Cleaner, Sub(i, ev) i.Cleaner = ev, v)
                End Sub
                Private Shared Sub _Cleaner_Refresh(d As __Job.DetailsClass)
                    d.RefreshNavigationProperty(__Job.DetailsClass.PropertySetProperties.Cleaner, d._Cleaner)
                End Sub
                Private Shared Sub _Cleaner_OnValueChanged(e As __Job)
                    e.Cleaner_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Client As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Job, __Job.DetailsClass, Global.LightSwitchApplication.Client).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Job, __Job.DetailsClass, Global.LightSwitchApplication.Client).Entry( _
                        "Client", _
                        AddressOf __Job.DetailsClass.PropertySetProperties._Client_Stub, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._Client_ComputeIsReadOnly, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._Client_Validate, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._Client_GetCoreImplementationValue, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._Client_GetImplementationValue, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._Client_SetImplementationValue, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._Client_Refresh, _
                        AddressOf __Job.DetailsClass.PropertySetProperties._Client_OnValueChanged)
                Private Shared Sub _Client_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Job.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Job, __Job.DetailsClass, Global.LightSwitchApplication.Client).Data), d As __Job.DetailsClass, sf As Object)
                    c(d, d._Client, sf)
                End Sub
                Private Shared Function _Client_ComputeIsReadOnly(e As __Job) As Boolean
                    Dim result As Boolean = False
                    e.Client_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Client_Validate(e As __Job, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Client_Validate(r)
                End Sub
                Private Shared Function _Client_GetCoreImplementationValue(d as __Job.DetailsClass) As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
                    Return d.ImplementationEntity.Client
                End Function
                Private Shared Function _Client_GetImplementationValue(d as __Job.DetailsClass) As Global.LightSwitchApplication.Client
                    Return d.GetImplementationValue(Of Global.LightSwitchApplication.Client, Global.LightSwitchApplication.Client.DetailsClass)(__Job.DetailsClass.PropertySetProperties.Client, d._Client)
                End Function
                Private Shared Sub _Client_SetImplementationValue(d As __Job.DetailsClass, v As Global.LightSwitchApplication.Client)
                    d.SetImplementationValue(__Job.DetailsClass.PropertySetProperties.Client, d._Client, Sub(i, ev) i.Client = ev, v)
                End Sub
                Private Shared Sub _Client_Refresh(d As __Job.DetailsClass)
                    d.RefreshNavigationProperty(__Job.DetailsClass.PropertySetProperties.Client, d._Client)
                End Sub
                Private Shared Sub _Client_OnValueChanged(e As __Job)
                    e.Client_Changed()
                End Sub
    
            End Class
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Id As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, Integer).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _StartTime As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, Date).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _EndTime As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, Date).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Price As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, Decimal).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _CleanersRate As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, Decimal).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _PerPeriod As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Recurance As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Note As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _QueryString As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _IsDeleted As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Job, __Job.DetailsClass, Boolean).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Cleaner As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Job, __Job.DetailsClass, Global.LightSwitchApplication.Cleaner).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Client As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Job, __Job.DetailsClass, Global.LightSwitchApplication.Client).Data
            
        End Class
    
        #End Region
    
    End Class
    
    #End Region
End Namespace
