
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports __Client = LightSwitchApplication.Client

Namespace LightSwitchApplication

    #Region "Entities"
    
    ''' <summary>
    ''' No Modeled Description Available
    ''' </summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
    Public NotInheritable Partial Class Client
        Inherits Global.Microsoft.LightSwitch.Framework.Base.EntityObject(Of __Client, __Client.DetailsClass)
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Initializes a new instance of the Client entity.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New()
            Me.New(Nothing)
        End Sub
    
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New(entitySet As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __Client))
            MyBase.New(entitySet)
            
            __Client.DetailsClass.Initialize(Me)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Client_Created()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Client_AllowSaveWithErrors(ByRef result As Boolean)
        End Sub
    
        #End Region
    
        #Region "Private Properties"
        
        ''' <summary>
        ''' Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property Application As Global.Microsoft.LightSwitch.IApplication(Of Global.LightSwitchApplication.DataWorkspace)
            Get
                Return Global.LightSwitchApplication.Application.Current
            End Get
        End Property
        
        ''' <summary>
        ''' Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property DataWorkspace As Global.LightSwitchApplication.DataWorkspace
            Get
                Return DirectCast(Me.Details.EntitySet.Details.DataService.Details.DataWorkspace, Global.LightSwitchApplication.DataWorkspace)
            End Get
        End Property
        
        #End Region
    
        #Region "Public Properties"
    
        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Id As Integer
            Get
                Return __Client.DetailsClass.GetValue(Me, __Client.DetailsClass.PropertySetProperties.Id)
            End Get
            Set
                __Client.DetailsClass.SetValue(Me, __Client.DetailsClass.PropertySetProperties.Id, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Id_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Id_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Id_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Name As String
            Get
                Return __Client.DetailsClass.GetValue(Me, __Client.DetailsClass.PropertySetProperties.Name)
            End Get
            Set
                __Client.DetailsClass.SetValue(Me, __Client.DetailsClass.PropertySetProperties.Name, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Name_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Name_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Name_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Address1 As String
            Get
                Return __Client.DetailsClass.GetValue(Me, __Client.DetailsClass.PropertySetProperties.Address1)
            End Get
            Set
                __Client.DetailsClass.SetValue(Me, __Client.DetailsClass.PropertySetProperties.Address1, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Address1_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Address1_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Address1_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Address2 As String
            Get
                Return __Client.DetailsClass.GetValue(Me, __Client.DetailsClass.PropertySetProperties.Address2)
            End Get
            Set
                __Client.DetailsClass.SetValue(Me, __Client.DetailsClass.PropertySetProperties.Address2, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Address2_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Address2_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Address2_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property City As String
            Get
                Return __Client.DetailsClass.GetValue(Me, __Client.DetailsClass.PropertySetProperties.City)
            End Get
            Set
                __Client.DetailsClass.SetValue(Me, __Client.DetailsClass.PropertySetProperties.City, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub City_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub City_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub City_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Postcode As String
            Get
                Return __Client.DetailsClass.GetValue(Me, __Client.DetailsClass.PropertySetProperties.Postcode)
            End Get
            Set
                __Client.DetailsClass.SetValue(Me, __Client.DetailsClass.PropertySetProperties.Postcode, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Postcode_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Postcode_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Postcode_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Region As String
            Get
                Return __Client.DetailsClass.GetValue(Me, __Client.DetailsClass.PropertySetProperties.Region)
            End Get
            Set
                __Client.DetailsClass.SetValue(Me, __Client.DetailsClass.PropertySetProperties.Region, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Region_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Region_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Region_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Phone As String
            Get
                Return __Client.DetailsClass.GetValue(Me, __Client.DetailsClass.PropertySetProperties.Phone)
            End Get
            Set
                __Client.DetailsClass.SetValue(Me, __Client.DetailsClass.PropertySetProperties.Phone, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Phone_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Phone_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Phone_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Email As String
            Get
                Return __Client.DetailsClass.GetValue(Me, __Client.DetailsClass.PropertySetProperties.Email)
            End Get
            Set
                __Client.DetailsClass.SetValue(Me, __Client.DetailsClass.PropertySetProperties.Email, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Email_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Email_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Email_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property QueryString As String
            Get
                Return __Client.DetailsClass.GetValue(Me, __Client.DetailsClass.PropertySetProperties.QueryString)
            End Get
            Set
                __Client.DetailsClass.SetValue(Me, __Client.DetailsClass.PropertySetProperties.QueryString, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub QueryString_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub QueryString_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub QueryString_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property Jobs As Global.Microsoft.LightSwitch.Framework.EntityCollection(Of Global.LightSwitchApplication.Job)
            Get
                Return __Client.DetailsClass.GetValue(Me, __Client.DetailsClass.PropertySetProperties.Jobs)
            End Get
        End Property
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property JobsQuery As Microsoft.LightSwitch.IDataServiceQueryable(Of Global.LightSwitchApplication.Job)
            Get
                Return __Client.DetailsClass.GetQuery(Me, __Client.DetailsClass.PropertySetProperties.Jobs)
            End Get
        End Property

        #End Region
    
        #Region "Details Class"
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of _
                __Client, _
                __Client.DetailsClass, _
                __Client.DetailsClass.IImplementation, _
                __Client.DetailsClass.PropertySet, _
                Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __Client, __Client.DetailsClass), _
                Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __Client, __Client.DetailsClass))
    
            Shared Sub New()
                Dim initializeEntry = __Client.DetailsClass.PropertySetProperties.Id
            End Sub
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private Shared ReadOnly __ClientEntry As Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __Client, __Client.DetailsClass).Entry = _
                New Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __Client, __Client.DetailsClass).Entry( _
                    AddressOf __Client.DetailsClass.__Client_CreateNew, _
                    AddressOf __Client.DetailsClass.__Client_Created, _
                    AddressOf __Client.DetailsClass.__Client_AllowSaveWithErrors)
            Private Shared Function __Client_CreateNew(es As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __Client)) As __Client
                Return New __Client(es)
            End Function
            Private Shared Sub __Client_Created(e As __Client)
                e.Client_Created()
            End Sub
            Private Shared Function __Client_AllowSaveWithErrors(e As __Client) As Boolean
                Dim result As Boolean = False
                e.Client_AllowSaveWithErrors(result)
                Return result
            End Function
    
            Public Sub New()
                MyBase.New()
            End Sub
    
            Public ReadOnly Shadows Property Commands As Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __Client, __Client.DetailsClass)
                Get
                    Return MyBase.Commands
                End Get
            End Property
    
            Public ReadOnly Shadows Property Methods As Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __Client, __Client.DetailsClass)
                Get
                    Return MyBase.Methods
                End Get
            End Property
    
            Public ReadOnly Shadows Property Properties As __Client.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet(Of __Client, __Client.DetailsClass)
    
                Public Sub New()
                    MyBase.New()
                End Sub
    
                Public ReadOnly Property Id As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, Integer)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Client.DetailsClass.PropertySetProperties.Id),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, Integer))
                    End Get
                End Property
                
                Public ReadOnly Property Name As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Client.DetailsClass.PropertySetProperties.Name),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Address1 As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Client.DetailsClass.PropertySetProperties.Address1),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Address2 As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Client.DetailsClass.PropertySetProperties.Address2),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property City As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Client.DetailsClass.PropertySetProperties.City),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Postcode As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Client.DetailsClass.PropertySetProperties.Postcode),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Region As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Client.DetailsClass.PropertySetProperties.Region),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Phone As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Client.DetailsClass.PropertySetProperties.Phone),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Email As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Client.DetailsClass.PropertySetProperties.Email),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property QueryString As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Client.DetailsClass.PropertySetProperties.QueryString),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Jobs As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Client, __Client.DetailsClass, Global.LightSwitchApplication.Job)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Client.DetailsClass.PropertySetProperties.Jobs),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Client, __Client.DetailsClass, Global.LightSwitchApplication.Job))
                    End Get
                End Property
                
            End Class
    
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            Public Interface IImplementation
                Inherits Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
                Shadows Property Id As Integer
                Shadows Property Name As String
                Shadows Property Address1 As String
                Shadows Property Address2 As String
                Shadows Property City As String
                Shadows Property Postcode As String
                Shadows Property Region As String
                Shadows Property Phone As String
                Shadows Property Email As String
                Shadows Property QueryString As String
                Shadows ReadOnly Property Jobs As Global.System.Collections.IEnumerable
    
            End Interface
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend Class PropertySetProperties
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Id As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, Integer).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, Integer).Entry( _
                        "Id", _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Id_Stub, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Id_Validate, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Id_GetImplementationValue, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Id_SetImplementationValue, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Id_OnValueChanged)
                Private Shared Sub _Id_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Client.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, Integer).Data), d As __Client.DetailsClass, sf As Object)
                    c(d, d._Id, sf)
                End Sub
                Private Shared Function _Id_ComputeIsReadOnly(e As __Client) As Boolean
                    Dim result As Boolean = False
                    e.Id_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Id_Validate(e As __Client, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Id_Validate(r)
                End Sub
                Private Shared Function _Id_GetImplementationValue(d As __Client.DetailsClass) As Integer
                    Return d.ImplementationEntity.Id
                End Function
                Private Shared Sub _Id_SetImplementationValue(d As __Client.DetailsClass, v As Integer)
                    d.ImplementationEntity.Id = v
                End Sub
                Private Shared Sub _Id_OnValueChanged(e As __Client)
                    e.Id_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Name As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String).Entry( _
                        "Name", _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Name_Stub, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Name_ComputeIsReadOnly, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Name_Validate, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Name_GetImplementationValue, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Name_SetImplementationValue, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Name_OnValueChanged)
                Private Shared Sub _Name_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Client.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String).Data), d As __Client.DetailsClass, sf As Object)
                    c(d, d._Name, sf)
                End Sub
                Private Shared Function _Name_ComputeIsReadOnly(e As __Client) As Boolean
                    Dim result As Boolean = False
                    e.Name_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Name_Validate(e As __Client, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Name_Validate(r)
                End Sub
                Private Shared Function _Name_GetImplementationValue(d As __Client.DetailsClass) As String
                    Return d.ImplementationEntity.Name
                End Function
                Private Shared Sub _Name_SetImplementationValue(d As __Client.DetailsClass, v As String)
                    d.ImplementationEntity.Name = v
                End Sub
                Private Shared Sub _Name_OnValueChanged(e As __Client)
                    e.Name_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Address1 As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String).Entry( _
                        "Address1", _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Address1_Stub, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Address1_ComputeIsReadOnly, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Address1_Validate, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Address1_GetImplementationValue, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Address1_SetImplementationValue, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Address1_OnValueChanged)
                Private Shared Sub _Address1_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Client.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String).Data), d As __Client.DetailsClass, sf As Object)
                    c(d, d._Address1, sf)
                End Sub
                Private Shared Function _Address1_ComputeIsReadOnly(e As __Client) As Boolean
                    Dim result As Boolean = False
                    e.Address1_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Address1_Validate(e As __Client, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Address1_Validate(r)
                End Sub
                Private Shared Function _Address1_GetImplementationValue(d As __Client.DetailsClass) As String
                    Return d.ImplementationEntity.Address1
                End Function
                Private Shared Sub _Address1_SetImplementationValue(d As __Client.DetailsClass, v As String)
                    d.ImplementationEntity.Address1 = v
                End Sub
                Private Shared Sub _Address1_OnValueChanged(e As __Client)
                    e.Address1_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Address2 As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String).Entry( _
                        "Address2", _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Address2_Stub, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Address2_ComputeIsReadOnly, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Address2_Validate, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Address2_GetImplementationValue, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Address2_SetImplementationValue, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Address2_OnValueChanged)
                Private Shared Sub _Address2_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Client.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String).Data), d As __Client.DetailsClass, sf As Object)
                    c(d, d._Address2, sf)
                End Sub
                Private Shared Function _Address2_ComputeIsReadOnly(e As __Client) As Boolean
                    Dim result As Boolean = False
                    e.Address2_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Address2_Validate(e As __Client, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Address2_Validate(r)
                End Sub
                Private Shared Function _Address2_GetImplementationValue(d As __Client.DetailsClass) As String
                    Return d.ImplementationEntity.Address2
                End Function
                Private Shared Sub _Address2_SetImplementationValue(d As __Client.DetailsClass, v As String)
                    d.ImplementationEntity.Address2 = v
                End Sub
                Private Shared Sub _Address2_OnValueChanged(e As __Client)
                    e.Address2_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly City As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String).Entry( _
                        "City", _
                        AddressOf __Client.DetailsClass.PropertySetProperties._City_Stub, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._City_ComputeIsReadOnly, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._City_Validate, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._City_GetImplementationValue, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._City_SetImplementationValue, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._City_OnValueChanged)
                Private Shared Sub _City_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Client.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String).Data), d As __Client.DetailsClass, sf As Object)
                    c(d, d._City, sf)
                End Sub
                Private Shared Function _City_ComputeIsReadOnly(e As __Client) As Boolean
                    Dim result As Boolean = False
                    e.City_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _City_Validate(e As __Client, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.City_Validate(r)
                End Sub
                Private Shared Function _City_GetImplementationValue(d As __Client.DetailsClass) As String
                    Return d.ImplementationEntity.City
                End Function
                Private Shared Sub _City_SetImplementationValue(d As __Client.DetailsClass, v As String)
                    d.ImplementationEntity.City = v
                End Sub
                Private Shared Sub _City_OnValueChanged(e As __Client)
                    e.City_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Postcode As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String).Entry( _
                        "Postcode", _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Postcode_Stub, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Postcode_ComputeIsReadOnly, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Postcode_Validate, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Postcode_GetImplementationValue, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Postcode_SetImplementationValue, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Postcode_OnValueChanged)
                Private Shared Sub _Postcode_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Client.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String).Data), d As __Client.DetailsClass, sf As Object)
                    c(d, d._Postcode, sf)
                End Sub
                Private Shared Function _Postcode_ComputeIsReadOnly(e As __Client) As Boolean
                    Dim result As Boolean = False
                    e.Postcode_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Postcode_Validate(e As __Client, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Postcode_Validate(r)
                End Sub
                Private Shared Function _Postcode_GetImplementationValue(d As __Client.DetailsClass) As String
                    Return d.ImplementationEntity.Postcode
                End Function
                Private Shared Sub _Postcode_SetImplementationValue(d As __Client.DetailsClass, v As String)
                    d.ImplementationEntity.Postcode = v
                End Sub
                Private Shared Sub _Postcode_OnValueChanged(e As __Client)
                    e.Postcode_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Region As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String).Entry( _
                        "Region", _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Region_Stub, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Region_ComputeIsReadOnly, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Region_Validate, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Region_GetImplementationValue, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Region_SetImplementationValue, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Region_OnValueChanged)
                Private Shared Sub _Region_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Client.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String).Data), d As __Client.DetailsClass, sf As Object)
                    c(d, d._Region, sf)
                End Sub
                Private Shared Function _Region_ComputeIsReadOnly(e As __Client) As Boolean
                    Dim result As Boolean = False
                    e.Region_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Region_Validate(e As __Client, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Region_Validate(r)
                End Sub
                Private Shared Function _Region_GetImplementationValue(d As __Client.DetailsClass) As String
                    Return d.ImplementationEntity.Region
                End Function
                Private Shared Sub _Region_SetImplementationValue(d As __Client.DetailsClass, v As String)
                    d.ImplementationEntity.Region = v
                End Sub
                Private Shared Sub _Region_OnValueChanged(e As __Client)
                    e.Region_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Phone As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String).Entry( _
                        "Phone", _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Phone_Stub, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Phone_ComputeIsReadOnly, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Phone_Validate, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Phone_GetImplementationValue, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Phone_SetImplementationValue, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Phone_OnValueChanged)
                Private Shared Sub _Phone_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Client.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String).Data), d As __Client.DetailsClass, sf As Object)
                    c(d, d._Phone, sf)
                End Sub
                Private Shared Function _Phone_ComputeIsReadOnly(e As __Client) As Boolean
                    Dim result As Boolean = False
                    e.Phone_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Phone_Validate(e As __Client, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Phone_Validate(r)
                End Sub
                Private Shared Function _Phone_GetImplementationValue(d As __Client.DetailsClass) As String
                    Return d.ImplementationEntity.Phone
                End Function
                Private Shared Sub _Phone_SetImplementationValue(d As __Client.DetailsClass, v As String)
                    d.ImplementationEntity.Phone = v
                End Sub
                Private Shared Sub _Phone_OnValueChanged(e As __Client)
                    e.Phone_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Email As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String).Entry( _
                        "Email", _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Email_Stub, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Email_ComputeIsReadOnly, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Email_Validate, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Email_GetImplementationValue, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Email_SetImplementationValue, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Email_OnValueChanged)
                Private Shared Sub _Email_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Client.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String).Data), d As __Client.DetailsClass, sf As Object)
                    c(d, d._Email, sf)
                End Sub
                Private Shared Function _Email_ComputeIsReadOnly(e As __Client) As Boolean
                    Dim result As Boolean = False
                    e.Email_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Email_Validate(e As __Client, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Email_Validate(r)
                End Sub
                Private Shared Function _Email_GetImplementationValue(d As __Client.DetailsClass) As String
                    Return d.ImplementationEntity.Email
                End Function
                Private Shared Sub _Email_SetImplementationValue(d As __Client.DetailsClass, v As String)
                    d.ImplementationEntity.Email = v
                End Sub
                Private Shared Sub _Email_OnValueChanged(e As __Client)
                    e.Email_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly QueryString As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String).Entry( _
                        "QueryString", _
                        AddressOf __Client.DetailsClass.PropertySetProperties._QueryString_Stub, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._QueryString_ComputeIsReadOnly, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._QueryString_Validate, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._QueryString_GetImplementationValue, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._QueryString_SetImplementationValue, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._QueryString_OnValueChanged)
                Private Shared Sub _QueryString_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Client.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String).Data), d As __Client.DetailsClass, sf As Object)
                    c(d, d._QueryString, sf)
                End Sub
                Private Shared Function _QueryString_ComputeIsReadOnly(e As __Client) As Boolean
                    Dim result As Boolean = False
                    e.QueryString_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _QueryString_Validate(e As __Client, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.QueryString_Validate(r)
                End Sub
                Private Shared Function _QueryString_GetImplementationValue(d As __Client.DetailsClass) As String
                    Return d.ImplementationEntity.QueryString
                End Function
                Private Shared Sub _QueryString_SetImplementationValue(d As __Client.DetailsClass, v As String)
                    d.ImplementationEntity.QueryString = v
                End Sub
                Private Shared Sub _QueryString_OnValueChanged(e As __Client)
                    e.QueryString_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Jobs As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Client, __Client.DetailsClass, Global.LightSwitchApplication.Job).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Client, __Client.DetailsClass, Global.LightSwitchApplication.Job).Entry( _
                        "Jobs", _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Jobs_Stub, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Jobs_GetReferencedEntities, _
                        AddressOf __Client.DetailsClass.PropertySetProperties._Jobs_GetEntityCollection)
                Private Shared Sub _Jobs_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Client.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Client, __Client.DetailsClass, Global.LightSwitchApplication.Job).Data), d As __Client.DetailsClass, sf As Object)
                    c(d, d._Jobs, sf)
                End Sub
                Private Shared Function _Jobs_GetReferencedEntities(d As __Client.DetailsClass) As Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.Job)
                    Return d.GetReferencedEntities(Of Global.LightSwitchApplication.Job, Global.LightSwitchApplication.Job.DetailsClass)(__Client.DetailsClass.PropertySetProperties.Jobs, d._Jobs)
                End Function
                Private Shared Function _Jobs_GetEntityCollection(d As __Client.DetailsClass) As Global.System.Collections.IEnumerable
                    Return d.ImplementationEntity.Jobs
                End Function
    
            End Class
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Id As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, Integer).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Name As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Address1 As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Address2 As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _City As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Postcode As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Region As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Phone As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Email As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _QueryString As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Client, __Client.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Jobs As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Client, __Client.DetailsClass, Global.LightSwitchApplication.Job).Data
            
        End Class
    
        #End Region
    
    End Class
    
    #End Region
End Namespace
