'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports __CleanersJobDetail = LightSwitchApplication.CleanersJobDetail
Imports __CreateNewJob = LightSwitchApplication.CreateNewJob
Imports __AllJobs = LightSwitchApplication.AllJobs
Imports __CreateNewClient = LightSwitchApplication.CreateNewClient

Namespace LightSwitchApplication

    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
    Partial Public NotInheritable Class CleanersJobDetail
        Inherits Global.Microsoft.LightSwitch.Framework.Client.ScreenObject(Of __CleanersJobDetail, __CleanersJobDetail.DetailsClass)

        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private Sub New()
            MyBase.New("LightSwitchApplication:CleanersJobDetail")
            __CleanersJobDetail.DetailsClass.Initialize(Me)
        End Sub

        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        Public Shared Function CreateInstance() As CleanersJobDetail
            Return New __CleanersJobDetail( _
            )
        End Function

        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CleanersJobDetail_InitializeDataWorkspace(ByVal saveChangesTo As Global.System.Collections.Generic.List(Of Global.Microsoft.LightSwitch.IDataService))
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CleanersJobDetail_Created()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CleanersJobDetail_Activated()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CleanersJobDetail_Saving(ByRef handled As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CleanersJobDetail_Saved()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CleanersJobDetail_Closing(ByRef cancel As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CleanersJobDetail_SaveError(ByVal exception As Global.System.Exception, ByRef handled As Boolean)
        End Sub
     
        #Region "Private Properties"
        
        ''' <summary>
        ''' Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property Application As Global.LightSwitchApplication.Application
            Get
                Return Global.LightSwitchApplication.Application.Current
            End Get
        End Property
        
        ''' <summary>
        ''' Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property DataWorkspace As Global.LightSwitchApplication.DataWorkspace
            Get
                Return DirectCast(DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IScreenDetails).DataWorkspace, Global.LightSwitchApplication.DataWorkspace)
            End Get
        End Property
        
        #End Region
 
        Partial Private Sub Cleaners_SelectionChanged()
        End Sub

        Partial Private Sub Cleaners_Changed(ByVal e As Global.System.Collections.Specialized.NotifyCollectionChangedEventArgs)
        End Sub

        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Cleaners_Loaded(ByVal succeeded As Boolean)
        End Sub

        Partial Private Sub Jobs_SelectionChanged()
        End Sub

        Partial Private Sub Jobs_Changed(ByVal e As Global.System.Collections.Specialized.NotifyCollectionChangedEventArgs)
        End Sub

        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Jobs_Loaded(ByVal succeeded As Boolean)
        End Sub

        ''' <summary>
        ''' Gets the Cleaners visual collection. The collection contains all records currently shown on the respective list or grid control.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property Cleaners As Global.Microsoft.LightSwitch.Framework.Client.VisualCollection(Of Global.LightSwitchApplication.Cleaner)
            Get
                Return __CleanersJobDetail.DetailsClass.GetValue(Me, __CleanersJobDetail.DetailsClass.PropertySetProperties.Cleaners)
            End Get
        End Property
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Cleaners_Validate(ByVal results As Global.Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder)
        End Sub
 
        ''' <summary>
        ''' Gets the Jobs visual collection. The collection contains all records currently shown on the respective list or grid control.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property Jobs As Global.Microsoft.LightSwitch.Framework.Client.VisualCollection(Of Global.LightSwitchApplication.Job)
            Get
                Return __CleanersJobDetail.DetailsClass.GetValue(Me, __CleanersJobDetail.DetailsClass.PropertySetProperties.Jobs)
            End Get
        End Property
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Jobs_Validate(ByVal results As Global.Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder)
        End Sub
 
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails(Of __CleanersJobDetail, __CleanersJobDetail.DetailsClass, __CleanersJobDetail.DetailsClass.PropertySet, __CleanersJobDetail.DetailsClass.CommandSet, __CleanersJobDetail.DetailsClass.MethodSet)

            Shared Sub New()
                Dim initializePropertyEntry = __CleanersJobDetail.DetailsClass.PropertySetProperties.Cleaners
            End Sub

            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private Shared ReadOnly __CleanersJobDetailEntry As Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails(Of __CleanersJobDetail, __CleanersJobDetail.DetailsClass).Entry = _
                New Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails(Of __CleanersJobDetail, __CleanersJobDetail.DetailsClass).Entry( _
                    AddressOf __CleanersJobDetail.DetailsClass.__CleanersJobDetail_InvokeInitializeDataWorkspace,
                    AddressOf __CleanersJobDetail.DetailsClass.__CleanersJobDetail_InvokeSavingEvent,
                    AddressOf __CleanersJobDetail.DetailsClass.__CleanersJobDetail_InvokeSavedEvent,
                    AddressOf __CleanersJobDetail.DetailsClass.__CleanersJobDetail_InvokeClosingEvent,
                    AddressOf __CleanersJobDetail.DetailsClass.__CleanersJobDetail_InvokeCreated,
                    AddressOf __CleanersJobDetail.DetailsClass.__CleanersJobDetail_InvokeActivated,
                    AddressOf __CleanersJobDetail.DetailsClass.__CleanersJobDetail_InvokeSaveErrorEvent)
            Private Shared Sub __CleanersJobDetail_InvokeInitializeDataWorkspace(s As __CleanersJobDetail, saveChangesTo As Global.System.Collections.Generic.List(Of Global.Microsoft.LightSwitch.IDataService))
                s.CleanersJobDetail_InitializeDataWorkspace(saveChangesTo)
            End Sub
            Private Shared Function __CleanersJobDetail_InvokeSavingEvent(s As __CleanersJobDetail) As Boolean
                Dim handled = False
                s.CleanersJobDetail_Saving(handled)
                Return handled
            End Function
            Private Shared Sub __CleanersJobDetail_InvokeSavedEvent(s As __CleanersJobDetail)
                s.CleanersJobDetail_Saved()
            End Sub
            Private Shared Function __CleanersJobDetail_InvokeClosingEvent(s As __CleanersJobDetail) As Boolean
                Dim cancel = False
                s.CleanersJobDetail_Closing(cancel)
                Return cancel
            End Function
            Private Shared Sub __CleanersJobDetail_InvokeCreated(s As __CleanersJobDetail)
                s.CleanersJobDetail_Created()
            End Sub
            Private Shared Sub __CleanersJobDetail_InvokeActivated(s As __CleanersJobDetail)
                s.CleanersJobDetail_Activated()
            End Sub
            Private Shared Function __CleanersJobDetail_InvokeSaveErrorEvent(s As __CleanersJobDetail, ex As Global.System.Exception) As Boolean
                Dim handled = False
                s.CleanersJobDetail_SaveError(ex, handled)
                Return handled
            End Function

            Public Sub New()
                MyBase.New()
            End Sub

            Public Shadows ReadOnly Property Properties As __CleanersJobDetail.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property

            Public Shadows ReadOnly Property Commands As __CleanersJobDetail.DetailsClass.CommandSet
                Get
                    Return MyBase.Commands
                End Get
            End Property

            Public Shadows ReadOnly Property Methods As __CleanersJobDetail.DetailsClass.MethodSet
                Get
                    Return MyBase.Methods
                End Get
            End Property

            Private Function CleanersQuery() As Global.Microsoft.LightSwitch.IDataServiceQueryable
                Return Me.Screen.DataWorkspace.ApplicationData.Cleaners
            End Function

            Private Function JobsQuery() As Global.Microsoft.LightSwitch.IDataServiceQueryable
                If Me.Screen.Cleaners.SelectedItem Is Nothing Then
                    Return Nothing
                End If

                Dim loader As Global.Microsoft.LightSwitch.IDataServiceQueryable(Of Global.LightSwitchApplication.Job) = _
                    DirectCast(DirectCast(Me.Screen.Cleaners.SelectedItem.Details.Properties.Jobs, Global.Microsoft.LightSwitch.Details.ILoadableProperty).Loader, Global.Microsoft.LightSwitch.IDataServiceQueryable(Of Global.LightSwitchApplication.Job))
                If loader Is Nothing Then
                    Return Nothing
                End If

                Dim startOfWeek1 As Date = Global.Microsoft.LightSwitch.RelativeDates.StartOfWeek()
                Dim endOfWeek1 As Date = Global.Microsoft.LightSwitch.RelativeDates.EndOfWeek()
                Return Global.Microsoft.LightSwitch.DataServiceQueryable.Include(
                    Global.Microsoft.LightSwitch.DataServiceQueryable.Where( _
                        loader, _
                        Function(j) ((j.StartTime >= startOfWeek1) AndAlso (j.StartTime <= endOfWeek1))),
                    "Client")
            End Function

            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)>
            Private _Cleaners As Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty(Of __CleanersJobDetail, __CleanersJobDetail.DetailsClass, Global.LightSwitchApplication.Cleaner).Data

            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)>
            Private _Jobs As Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty(Of __CleanersJobDetail, __CleanersJobDetail.DetailsClass, Global.LightSwitchApplication.Job).Data

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet(Of __CleanersJobDetail, __CleanersJobDetail.DetailsClass)

                Public ReadOnly Property Cleaners As Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty(Of __CleanersJobDetail, __CleanersJobDetail.DetailsClass, Global.LightSwitchApplication.Cleaner)
                    Get
                        Return DirectCast(MyBase.GetItem(__CleanersJobDetail.DetailsClass.PropertySetProperties.Cleaners), Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty(Of __CleanersJobDetail, __CleanersJobDetail.DetailsClass, Global.LightSwitchApplication.Cleaner))
                    End Get
                End Property

                Public ReadOnly Property Jobs As Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty(Of __CleanersJobDetail, __CleanersJobDetail.DetailsClass, Global.LightSwitchApplication.Job)
                    Get
                        Return DirectCast(MyBase.GetItem(__CleanersJobDetail.DetailsClass.PropertySetProperties.Jobs), Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty(Of __CleanersJobDetail, __CleanersJobDetail.DetailsClass, Global.LightSwitchApplication.Job))
                    End Get
                End Property

            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class CommandSet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet(Of __CleanersJobDetail, __CleanersJobDetail.DetailsClass)
            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class MethodSet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet(Of __CleanersJobDetail, __CleanersJobDetail.DetailsClass)
            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend NotInheritable Class PropertySetProperties

                Public Shared ReadOnly Cleaners As New Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty(Of __CleanersJobDetail, __CleanersJobDetail.DetailsClass, Global.LightSwitchApplication.Cleaner).Entry( _
                    "Cleaners",
                    AddressOf __CleanersJobDetail.DetailsClass.PropertySetProperties._Cleaners_Stub,
                    AddressOf __CleanersJobDetail.DetailsClass.PropertySetProperties._Cleaners_Validate,
                    AddressOf __CleanersJobDetail.DetailsClass.PropertySetProperties._Cleaners_CreateQuery,
                    AddressOf __CleanersJobDetail.DetailsClass.PropertySetProperties._Cleaners_SelectionChanged,
                    AddressOf __CleanersJobDetail.DetailsClass.PropertySetProperties._Cleaners_OnCollectionChanged,
                    AddressOf __CleanersJobDetail.DetailsClass.PropertySetProperties._Cleaners_OnLoaded)
                Private Shared Sub _Cleaners_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __CleanersJobDetail.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty(Of __CleanersJobDetail, __CleanersJobDetail.DetailsClass, Global.LightSwitchApplication.Cleaner).Data), d As __CleanersJobDetail.DetailsClass, sf As Object)
                    c(d, d._Cleaners, sf)
                End Sub
                Private Shared Sub _Cleaners_Validate(s As __CleanersJobDetail, r As Global.Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder)
                    s.Cleaners_Validate(r)
                End Sub
                Private Shared Function _Cleaners_CreateQuery(d As __CleanersJobDetail.DetailsClass, args As Object()) As Global.Microsoft.LightSwitch.IDataServiceQueryable
                    Return d.CleanersQuery()
                End Function
                Private Shared Sub _Cleaners_SelectionChanged(s As __CleanersJobDetail)
                    s.Cleaners_SelectionChanged()
                End Sub
                Private Shared Sub _Cleaners_OnCollectionChanged(s As __CleanersJobDetail, e As Global.System.Collections.Specialized.NotifyCollectionChangedEventArgs)
                    s.Cleaners_Changed(e)
                End Sub
                Private Shared Sub _Cleaners_OnLoaded(s As __CleanersJobDetail, succeeded As Boolean)
                    s.Cleaners_Loaded(succeeded)
                End Sub

                Public Shared ReadOnly Jobs As New Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty(Of __CleanersJobDetail, __CleanersJobDetail.DetailsClass, Global.LightSwitchApplication.Job).Entry( _
                    "Jobs",
                    AddressOf __CleanersJobDetail.DetailsClass.PropertySetProperties._Jobs_Stub,
                    AddressOf __CleanersJobDetail.DetailsClass.PropertySetProperties._Jobs_Validate,
                    AddressOf __CleanersJobDetail.DetailsClass.PropertySetProperties._Jobs_CreateQuery,
                    AddressOf __CleanersJobDetail.DetailsClass.PropertySetProperties._Jobs_SelectionChanged,
                    AddressOf __CleanersJobDetail.DetailsClass.PropertySetProperties._Jobs_OnCollectionChanged,
                    AddressOf __CleanersJobDetail.DetailsClass.PropertySetProperties._Jobs_OnLoaded)
                Private Shared Sub _Jobs_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __CleanersJobDetail.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty(Of __CleanersJobDetail, __CleanersJobDetail.DetailsClass, Global.LightSwitchApplication.Job).Data), d As __CleanersJobDetail.DetailsClass, sf As Object)
                    c(d, d._Jobs, sf)
                End Sub
                Private Shared Sub _Jobs_Validate(s As __CleanersJobDetail, r As Global.Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder)
                    s.Jobs_Validate(r)
                End Sub
                Private Shared Function _Jobs_CreateQuery(d As __CleanersJobDetail.DetailsClass, args As Object()) As Global.Microsoft.LightSwitch.IDataServiceQueryable
                    Return d.JobsQuery()
                End Function
                Private Shared Sub _Jobs_SelectionChanged(s As __CleanersJobDetail)
                    s.Jobs_SelectionChanged()
                End Sub
                Private Shared Sub _Jobs_OnCollectionChanged(s As __CleanersJobDetail, e As Global.System.Collections.Specialized.NotifyCollectionChangedEventArgs)
                    s.Jobs_Changed(e)
                End Sub
                Private Shared Sub _Jobs_OnLoaded(s As __CleanersJobDetail, succeeded As Boolean)
                    s.Jobs_Loaded(succeeded)
                End Sub

            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend NotInheritable Class CommandSetProperties
            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend NotInheritable Class MethodSetProperties
            End Class

        End Class

    End Class

    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
    Partial Public NotInheritable Class CreateNewJob
        Inherits Global.Microsoft.LightSwitch.Framework.Client.ScreenObject(Of __CreateNewJob, __CreateNewJob.DetailsClass)

        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private Sub New()
            MyBase.New("LightSwitchApplication:CreateNewJob")
            __CreateNewJob.DetailsClass.Initialize(Me)
        End Sub

        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        Public Shared Function CreateInstance() As CreateNewJob
            Return New __CreateNewJob( _
            )
        End Function

        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreateNewJob_InitializeDataWorkspace(ByVal saveChangesTo As Global.System.Collections.Generic.List(Of Global.Microsoft.LightSwitch.IDataService))
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreateNewJob_Created()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreateNewJob_Activated()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreateNewJob_Saving(ByRef handled As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreateNewJob_Saved()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreateNewJob_Closing(ByRef cancel As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreateNewJob_SaveError(ByVal exception As Global.System.Exception, ByRef handled As Boolean)
        End Sub
     
        #Region "Private Properties"
        
        ''' <summary>
        ''' Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property Application As Global.LightSwitchApplication.Application
            Get
                Return Global.LightSwitchApplication.Application.Current
            End Get
        End Property
        
        ''' <summary>
        ''' Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property DataWorkspace As Global.LightSwitchApplication.DataWorkspace
            Get
                Return DirectCast(DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IScreenDetails).DataWorkspace, Global.LightSwitchApplication.DataWorkspace)
            End Get
        End Property
        
        #End Region
 
        Partial Private Sub JobProperty_Changed()
        End Sub

        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property JobProperty As Global.LightSwitchApplication.Job
            Get
                Return __CreateNewJob.DetailsClass.GetValue(Me, __CreateNewJob.DetailsClass.PropertySetProperties.JobProperty)
            End Get
            Set(ByVal value As Global.LightSwitchApplication.Job)
                __CreateNewJob.DetailsClass.SetValue(Me, __CreateNewJob.DetailsClass.PropertySetProperties.JobProperty, value)
            End Set
        End Property
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub JobProperty_Validate(ByVal results As Global.Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder)
        End Sub
 
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails(Of __CreateNewJob, __CreateNewJob.DetailsClass, __CreateNewJob.DetailsClass.PropertySet, __CreateNewJob.DetailsClass.CommandSet, __CreateNewJob.DetailsClass.MethodSet)

            Shared Sub New()
                Dim initializePropertyEntry = __CreateNewJob.DetailsClass.PropertySetProperties.JobProperty
            End Sub

            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private Shared ReadOnly __CreateNewJobEntry As Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails(Of __CreateNewJob, __CreateNewJob.DetailsClass).Entry = _
                New Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails(Of __CreateNewJob, __CreateNewJob.DetailsClass).Entry( _
                    AddressOf __CreateNewJob.DetailsClass.__CreateNewJob_InvokeInitializeDataWorkspace,
                    AddressOf __CreateNewJob.DetailsClass.__CreateNewJob_InvokeSavingEvent,
                    AddressOf __CreateNewJob.DetailsClass.__CreateNewJob_InvokeSavedEvent,
                    AddressOf __CreateNewJob.DetailsClass.__CreateNewJob_InvokeClosingEvent,
                    AddressOf __CreateNewJob.DetailsClass.__CreateNewJob_InvokeCreated,
                    AddressOf __CreateNewJob.DetailsClass.__CreateNewJob_InvokeActivated,
                    AddressOf __CreateNewJob.DetailsClass.__CreateNewJob_InvokeSaveErrorEvent)
            Private Shared Sub __CreateNewJob_InvokeInitializeDataWorkspace(s As __CreateNewJob, saveChangesTo As Global.System.Collections.Generic.List(Of Global.Microsoft.LightSwitch.IDataService))
                s.CreateNewJob_InitializeDataWorkspace(saveChangesTo)
            End Sub
            Private Shared Function __CreateNewJob_InvokeSavingEvent(s As __CreateNewJob) As Boolean
                Dim handled = False
                s.CreateNewJob_Saving(handled)
                Return handled
            End Function
            Private Shared Sub __CreateNewJob_InvokeSavedEvent(s As __CreateNewJob)
                s.CreateNewJob_Saved()
            End Sub
            Private Shared Function __CreateNewJob_InvokeClosingEvent(s As __CreateNewJob) As Boolean
                Dim cancel = False
                s.CreateNewJob_Closing(cancel)
                Return cancel
            End Function
            Private Shared Sub __CreateNewJob_InvokeCreated(s As __CreateNewJob)
                s.CreateNewJob_Created()
            End Sub
            Private Shared Sub __CreateNewJob_InvokeActivated(s As __CreateNewJob)
                s.CreateNewJob_Activated()
            End Sub
            Private Shared Function __CreateNewJob_InvokeSaveErrorEvent(s As __CreateNewJob, ex As Global.System.Exception) As Boolean
                Dim handled = False
                s.CreateNewJob_SaveError(ex, handled)
                Return handled
            End Function

            Public Sub New()
                MyBase.New()
            End Sub

            Public Shadows ReadOnly Property Properties As __CreateNewJob.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property

            Public Shadows ReadOnly Property Commands As __CreateNewJob.DetailsClass.CommandSet
                Get
                    Return MyBase.Commands
                End Get
            End Property

            Public Shadows ReadOnly Property Methods As __CreateNewJob.DetailsClass.MethodSet
                Get
                    Return MyBase.Methods
                End Get
            End Property

            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)>
            Private _JobProperty As Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty(Of __CreateNewJob, __CreateNewJob.DetailsClass, Global.LightSwitchApplication.Job).Data

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet(Of __CreateNewJob, __CreateNewJob.DetailsClass)

                Public ReadOnly Property JobProperty As Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty(Of __CreateNewJob, __CreateNewJob.DetailsClass, Global.LightSwitchApplication.Job)
                    Get
                        Return DirectCast(MyBase.GetItem(__CreateNewJob.DetailsClass.PropertySetProperties.JobProperty), Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty(Of __CreateNewJob, __CreateNewJob.DetailsClass, Global.LightSwitchApplication.Job))
                    End Get
                End Property

            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class CommandSet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet(Of __CreateNewJob, __CreateNewJob.DetailsClass)
            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class MethodSet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet(Of __CreateNewJob, __CreateNewJob.DetailsClass)
            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend NotInheritable Class PropertySetProperties

                Public Shared ReadOnly JobProperty As New Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty(Of __CreateNewJob, __CreateNewJob.DetailsClass, Global.LightSwitchApplication.Job).Entry( _
                    "JobProperty",
                    False,
                    AddressOf __CreateNewJob.DetailsClass.PropertySetProperties._JobProperty_Stub,
                    AddressOf __CreateNewJob.DetailsClass.PropertySetProperties._JobProperty_Validate,
                    AddressOf __CreateNewJob.DetailsClass.PropertySetProperties._JobProperty_OnValueChanged)
                Private Shared Sub _JobProperty_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __CreateNewJob.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty(Of __CreateNewJob, __CreateNewJob.DetailsClass, Global.LightSwitchApplication.Job).Data), d As __CreateNewJob.DetailsClass, sf As Object)
                    c(d, d._JobProperty, sf)
                End Sub
                Private Shared Sub _JobProperty_Validate(s As __CreateNewJob, r As Global.Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder)
                    s.JobProperty_Validate(r)
                End Sub
                Private Shared Sub _JobProperty_OnValueChanged(s As __CreateNewJob)
                    s.JobProperty_Changed()
                End Sub

            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend NotInheritable Class CommandSetProperties
            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend NotInheritable Class MethodSetProperties
            End Class

        End Class

    End Class

    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
    Partial Public NotInheritable Class AllJobs
        Inherits Global.Microsoft.LightSwitch.Framework.Client.ScreenObject(Of __AllJobs, __AllJobs.DetailsClass)

        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private Sub New()
            MyBase.New("LightSwitchApplication:AllJobs")
            __AllJobs.DetailsClass.Initialize(Me)
        End Sub

        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        Public Shared Function CreateInstance() As AllJobs
            Return New __AllJobs( _
            )
        End Function

        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub AllJobs_InitializeDataWorkspace(ByVal saveChangesTo As Global.System.Collections.Generic.List(Of Global.Microsoft.LightSwitch.IDataService))
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub AllJobs_Created()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub AllJobs_Activated()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub AllJobs_Saving(ByRef handled As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub AllJobs_Saved()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub AllJobs_Closing(ByRef cancel As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub AllJobs_SaveError(ByVal exception As Global.System.Exception, ByRef handled As Boolean)
        End Sub
     
        #Region "Private Properties"
        
        ''' <summary>
        ''' Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property Application As Global.LightSwitchApplication.Application
            Get
                Return Global.LightSwitchApplication.Application.Current
            End Get
        End Property
        
        ''' <summary>
        ''' Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property DataWorkspace As Global.LightSwitchApplication.DataWorkspace
            Get
                Return DirectCast(DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IScreenDetails).DataWorkspace, Global.LightSwitchApplication.DataWorkspace)
            End Get
        End Property
        
        #End Region
 
        Partial Private Sub Jobs_SelectionChanged()
        End Sub

        Partial Private Sub Jobs_Changed(ByVal e As Global.System.Collections.Specialized.NotifyCollectionChangedEventArgs)
        End Sub

        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Jobs_Loaded(ByVal succeeded As Boolean)
        End Sub

        ''' <summary>
        ''' Gets the Jobs visual collection. The collection contains all records currently shown on the respective list or grid control.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property Jobs As Global.Microsoft.LightSwitch.Framework.Client.VisualCollection(Of Global.LightSwitchApplication.Job)
            Get
                Return __AllJobs.DetailsClass.GetValue(Me, __AllJobs.DetailsClass.PropertySetProperties.Jobs)
            End Get
        End Property
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Jobs_Validate(ByVal results As Global.Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder)
        End Sub
 
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails(Of __AllJobs, __AllJobs.DetailsClass, __AllJobs.DetailsClass.PropertySet, __AllJobs.DetailsClass.CommandSet, __AllJobs.DetailsClass.MethodSet)

            Shared Sub New()
                Dim initializePropertyEntry = __AllJobs.DetailsClass.PropertySetProperties.Jobs
            End Sub

            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private Shared ReadOnly __AllJobsEntry As Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails(Of __AllJobs, __AllJobs.DetailsClass).Entry = _
                New Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails(Of __AllJobs, __AllJobs.DetailsClass).Entry( _
                    AddressOf __AllJobs.DetailsClass.__AllJobs_InvokeInitializeDataWorkspace,
                    AddressOf __AllJobs.DetailsClass.__AllJobs_InvokeSavingEvent,
                    AddressOf __AllJobs.DetailsClass.__AllJobs_InvokeSavedEvent,
                    AddressOf __AllJobs.DetailsClass.__AllJobs_InvokeClosingEvent,
                    AddressOf __AllJobs.DetailsClass.__AllJobs_InvokeCreated,
                    AddressOf __AllJobs.DetailsClass.__AllJobs_InvokeActivated,
                    AddressOf __AllJobs.DetailsClass.__AllJobs_InvokeSaveErrorEvent)
            Private Shared Sub __AllJobs_InvokeInitializeDataWorkspace(s As __AllJobs, saveChangesTo As Global.System.Collections.Generic.List(Of Global.Microsoft.LightSwitch.IDataService))
                s.AllJobs_InitializeDataWorkspace(saveChangesTo)
            End Sub
            Private Shared Function __AllJobs_InvokeSavingEvent(s As __AllJobs) As Boolean
                Dim handled = False
                s.AllJobs_Saving(handled)
                Return handled
            End Function
            Private Shared Sub __AllJobs_InvokeSavedEvent(s As __AllJobs)
                s.AllJobs_Saved()
            End Sub
            Private Shared Function __AllJobs_InvokeClosingEvent(s As __AllJobs) As Boolean
                Dim cancel = False
                s.AllJobs_Closing(cancel)
                Return cancel
            End Function
            Private Shared Sub __AllJobs_InvokeCreated(s As __AllJobs)
                s.AllJobs_Created()
            End Sub
            Private Shared Sub __AllJobs_InvokeActivated(s As __AllJobs)
                s.AllJobs_Activated()
            End Sub
            Private Shared Function __AllJobs_InvokeSaveErrorEvent(s As __AllJobs, ex As Global.System.Exception) As Boolean
                Dim handled = False
                s.AllJobs_SaveError(ex, handled)
                Return handled
            End Function

            Public Sub New()
                MyBase.New()
            End Sub

            Public Shadows ReadOnly Property Properties As __AllJobs.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property

            Public Shadows ReadOnly Property Commands As __AllJobs.DetailsClass.CommandSet
                Get
                    Return MyBase.Commands
                End Get
            End Property

            Public Shadows ReadOnly Property Methods As __AllJobs.DetailsClass.MethodSet
                Get
                    Return MyBase.Methods
                End Get
            End Property

            Private Function JobsQuery() As Global.Microsoft.LightSwitch.IDataServiceQueryable
                Return Global.Microsoft.LightSwitch.DataServiceQueryable.Include(
                    Global.Microsoft.LightSwitch.DataServiceQueryable.Include(
                        Me.Screen.DataWorkspace.ApplicationData.Jobs,
                        "Client"),
                    "Cleaner")
            End Function

            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)>
            Private _Jobs As Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty(Of __AllJobs, __AllJobs.DetailsClass, Global.LightSwitchApplication.Job).Data

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet(Of __AllJobs, __AllJobs.DetailsClass)

                Public ReadOnly Property Jobs As Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty(Of __AllJobs, __AllJobs.DetailsClass, Global.LightSwitchApplication.Job)
                    Get
                        Return DirectCast(MyBase.GetItem(__AllJobs.DetailsClass.PropertySetProperties.Jobs), Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty(Of __AllJobs, __AllJobs.DetailsClass, Global.LightSwitchApplication.Job))
                    End Get
                End Property

            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class CommandSet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet(Of __AllJobs, __AllJobs.DetailsClass)
            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class MethodSet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet(Of __AllJobs, __AllJobs.DetailsClass)
            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend NotInheritable Class PropertySetProperties

                Public Shared ReadOnly Jobs As New Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty(Of __AllJobs, __AllJobs.DetailsClass, Global.LightSwitchApplication.Job).Entry( _
                    "Jobs",
                    AddressOf __AllJobs.DetailsClass.PropertySetProperties._Jobs_Stub,
                    AddressOf __AllJobs.DetailsClass.PropertySetProperties._Jobs_Validate,
                    AddressOf __AllJobs.DetailsClass.PropertySetProperties._Jobs_CreateQuery,
                    AddressOf __AllJobs.DetailsClass.PropertySetProperties._Jobs_SelectionChanged,
                    AddressOf __AllJobs.DetailsClass.PropertySetProperties._Jobs_OnCollectionChanged,
                    AddressOf __AllJobs.DetailsClass.PropertySetProperties._Jobs_OnLoaded)
                Private Shared Sub _Jobs_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __AllJobs.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty(Of __AllJobs, __AllJobs.DetailsClass, Global.LightSwitchApplication.Job).Data), d As __AllJobs.DetailsClass, sf As Object)
                    c(d, d._Jobs, sf)
                End Sub
                Private Shared Sub _Jobs_Validate(s As __AllJobs, r As Global.Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder)
                    s.Jobs_Validate(r)
                End Sub
                Private Shared Function _Jobs_CreateQuery(d As __AllJobs.DetailsClass, args As Object()) As Global.Microsoft.LightSwitch.IDataServiceQueryable
                    Return d.JobsQuery()
                End Function
                Private Shared Sub _Jobs_SelectionChanged(s As __AllJobs)
                    s.Jobs_SelectionChanged()
                End Sub
                Private Shared Sub _Jobs_OnCollectionChanged(s As __AllJobs, e As Global.System.Collections.Specialized.NotifyCollectionChangedEventArgs)
                    s.Jobs_Changed(e)
                End Sub
                Private Shared Sub _Jobs_OnLoaded(s As __AllJobs, succeeded As Boolean)
                    s.Jobs_Loaded(succeeded)
                End Sub

            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend NotInheritable Class CommandSetProperties
            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend NotInheritable Class MethodSetProperties
            End Class

        End Class

    End Class

    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
    Partial Public NotInheritable Class CreateNewClient
        Inherits Global.Microsoft.LightSwitch.Framework.Client.ScreenObject(Of __CreateNewClient, __CreateNewClient.DetailsClass)

        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private Sub New()
            MyBase.New("LightSwitchApplication:CreateNewClient")
            __CreateNewClient.DetailsClass.Initialize(Me)
        End Sub

        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        Public Shared Function CreateInstance() As CreateNewClient
            Return New __CreateNewClient( _
            )
        End Function

        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreateNewClient_InitializeDataWorkspace(ByVal saveChangesTo As Global.System.Collections.Generic.List(Of Global.Microsoft.LightSwitch.IDataService))
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreateNewClient_Created()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreateNewClient_Activated()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreateNewClient_Saving(ByRef handled As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreateNewClient_Saved()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreateNewClient_Closing(ByRef cancel As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreateNewClient_SaveError(ByVal exception As Global.System.Exception, ByRef handled As Boolean)
        End Sub
     
        #Region "Private Properties"
        
        ''' <summary>
        ''' Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property Application As Global.LightSwitchApplication.Application
            Get
                Return Global.LightSwitchApplication.Application.Current
            End Get
        End Property
        
        ''' <summary>
        ''' Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property DataWorkspace As Global.LightSwitchApplication.DataWorkspace
            Get
                Return DirectCast(DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IScreenDetails).DataWorkspace, Global.LightSwitchApplication.DataWorkspace)
            End Get
        End Property
        
        #End Region
 
        Partial Private Sub ClientProperty_Changed()
        End Sub

        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property ClientProperty As Global.LightSwitchApplication.Client
            Get
                Return __CreateNewClient.DetailsClass.GetValue(Me, __CreateNewClient.DetailsClass.PropertySetProperties.ClientProperty)
            End Get
            Set(ByVal value As Global.LightSwitchApplication.Client)
                __CreateNewClient.DetailsClass.SetValue(Me, __CreateNewClient.DetailsClass.PropertySetProperties.ClientProperty, value)
            End Set
        End Property
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ClientProperty_Validate(ByVal results As Global.Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder)
        End Sub
 
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails(Of __CreateNewClient, __CreateNewClient.DetailsClass, __CreateNewClient.DetailsClass.PropertySet, __CreateNewClient.DetailsClass.CommandSet, __CreateNewClient.DetailsClass.MethodSet)

            Shared Sub New()
                Dim initializePropertyEntry = __CreateNewClient.DetailsClass.PropertySetProperties.ClientProperty
            End Sub

            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private Shared ReadOnly __CreateNewClientEntry As Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails(Of __CreateNewClient, __CreateNewClient.DetailsClass).Entry = _
                New Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails(Of __CreateNewClient, __CreateNewClient.DetailsClass).Entry( _
                    AddressOf __CreateNewClient.DetailsClass.__CreateNewClient_InvokeInitializeDataWorkspace,
                    AddressOf __CreateNewClient.DetailsClass.__CreateNewClient_InvokeSavingEvent,
                    AddressOf __CreateNewClient.DetailsClass.__CreateNewClient_InvokeSavedEvent,
                    AddressOf __CreateNewClient.DetailsClass.__CreateNewClient_InvokeClosingEvent,
                    AddressOf __CreateNewClient.DetailsClass.__CreateNewClient_InvokeCreated,
                    AddressOf __CreateNewClient.DetailsClass.__CreateNewClient_InvokeActivated,
                    AddressOf __CreateNewClient.DetailsClass.__CreateNewClient_InvokeSaveErrorEvent)
            Private Shared Sub __CreateNewClient_InvokeInitializeDataWorkspace(s As __CreateNewClient, saveChangesTo As Global.System.Collections.Generic.List(Of Global.Microsoft.LightSwitch.IDataService))
                s.CreateNewClient_InitializeDataWorkspace(saveChangesTo)
            End Sub
            Private Shared Function __CreateNewClient_InvokeSavingEvent(s As __CreateNewClient) As Boolean
                Dim handled = False
                s.CreateNewClient_Saving(handled)
                Return handled
            End Function
            Private Shared Sub __CreateNewClient_InvokeSavedEvent(s As __CreateNewClient)
                s.CreateNewClient_Saved()
            End Sub
            Private Shared Function __CreateNewClient_InvokeClosingEvent(s As __CreateNewClient) As Boolean
                Dim cancel = False
                s.CreateNewClient_Closing(cancel)
                Return cancel
            End Function
            Private Shared Sub __CreateNewClient_InvokeCreated(s As __CreateNewClient)
                s.CreateNewClient_Created()
            End Sub
            Private Shared Sub __CreateNewClient_InvokeActivated(s As __CreateNewClient)
                s.CreateNewClient_Activated()
            End Sub
            Private Shared Function __CreateNewClient_InvokeSaveErrorEvent(s As __CreateNewClient, ex As Global.System.Exception) As Boolean
                Dim handled = False
                s.CreateNewClient_SaveError(ex, handled)
                Return handled
            End Function

            Public Sub New()
                MyBase.New()
            End Sub

            Public Shadows ReadOnly Property Properties As __CreateNewClient.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property

            Public Shadows ReadOnly Property Commands As __CreateNewClient.DetailsClass.CommandSet
                Get
                    Return MyBase.Commands
                End Get
            End Property

            Public Shadows ReadOnly Property Methods As __CreateNewClient.DetailsClass.MethodSet
                Get
                    Return MyBase.Methods
                End Get
            End Property

            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)>
            Private _ClientProperty As Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty(Of __CreateNewClient, __CreateNewClient.DetailsClass, Global.LightSwitchApplication.Client).Data

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet(Of __CreateNewClient, __CreateNewClient.DetailsClass)

                Public ReadOnly Property ClientProperty As Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty(Of __CreateNewClient, __CreateNewClient.DetailsClass, Global.LightSwitchApplication.Client)
                    Get
                        Return DirectCast(MyBase.GetItem(__CreateNewClient.DetailsClass.PropertySetProperties.ClientProperty), Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty(Of __CreateNewClient, __CreateNewClient.DetailsClass, Global.LightSwitchApplication.Client))
                    End Get
                End Property

            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class CommandSet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet(Of __CreateNewClient, __CreateNewClient.DetailsClass)
            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class MethodSet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet(Of __CreateNewClient, __CreateNewClient.DetailsClass)
            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend NotInheritable Class PropertySetProperties

                Public Shared ReadOnly ClientProperty As New Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty(Of __CreateNewClient, __CreateNewClient.DetailsClass, Global.LightSwitchApplication.Client).Entry( _
                    "ClientProperty",
                    False,
                    AddressOf __CreateNewClient.DetailsClass.PropertySetProperties._ClientProperty_Stub,
                    AddressOf __CreateNewClient.DetailsClass.PropertySetProperties._ClientProperty_Validate,
                    AddressOf __CreateNewClient.DetailsClass.PropertySetProperties._ClientProperty_OnValueChanged)
                Private Shared Sub _ClientProperty_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __CreateNewClient.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty(Of __CreateNewClient, __CreateNewClient.DetailsClass, Global.LightSwitchApplication.Client).Data), d As __CreateNewClient.DetailsClass, sf As Object)
                    c(d, d._ClientProperty, sf)
                End Sub
                Private Shared Sub _ClientProperty_Validate(s As __CreateNewClient, r As Global.Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder)
                    s.ClientProperty_Validate(r)
                End Sub
                Private Shared Sub _ClientProperty_OnValueChanged(s As __CreateNewClient)
                    s.ClientProperty_Changed()
                End Sub

            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend NotInheritable Class CommandSetProperties
            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend NotInheritable Class MethodSetProperties
            End Class

        End Class

    End Class

End Namespace
