'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace LightSwitchApplication.Implementation
    
    #Region "Cleaner"
    <Global.System.Runtime.Serialization.DataContract(Namespace:="http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")> _
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public NotInheritable Class Cleaner
        Inherits Global.System.ServiceModel.DomainServices.Client.Entity
        Implements Global.LightSwitchApplication.Cleaner.DetailsClass.IImplementation
    
        Public Overrides Function GetIdentity() As Object
            If (Me.__host IsNot Nothing AndAlso Me.__host.IsNewlyAdded) Then
                Return Nothing
            End If
    
            Return Me._Id
        End Function
    
        <Global.System.ComponentModel.DataAnnotations.Key()> _
        <Global.System.ComponentModel.DataAnnotations.Editable(False, AllowInitialValue:=True)> _
        <Global.System.Runtime.Serialization.DataMember()> _
        <Global.System.ComponentModel.DataAnnotations.RoundtripOriginal()> _
        Public Property Id() As Integer Implements Global.LightSwitchApplication.Cleaner.DetailsClass.IImplementation.Id
            Get
                Return Me._Id
            End Get
            Set(ByVal value As Integer)
                If Not Global.System.Object.Equals(Me._Id, value) Then
                    Me.ValidateProperty("Id", value)
                    Me._Id = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        Private _Id As Integer
        
        <Global.System.Runtime.Serialization.DataMember()> _
        <Global.System.ComponentModel.DataAnnotations.RoundtripOriginal()> _
        Public Property QueryString() As String Implements Global.LightSwitchApplication.Cleaner.DetailsClass.IImplementation.QueryString
            Get
                Return Me._QueryString
            End Get
            Set(ByVal value As String)
                If Not Global.System.Object.Equals(Me._QueryString, value) Then
                    Me.RaiseDataMemberChanging("QueryString")
                    Me.ValidateProperty("QueryString", value)
                    Me._QueryString = value
                    Me.RaiseDataMemberChanged("QueryString")
                End If
            End Set
        End Property
        Private _QueryString As String
        
        <Global.System.Runtime.Serialization.DataMember()> _
        <Global.System.ComponentModel.DataAnnotations.RoundtripOriginal()> _
        Public Property FirstName() As String Implements Global.LightSwitchApplication.Cleaner.DetailsClass.IImplementation.FirstName
            Get
                Return Me._FirstName
            End Get
            Set(ByVal value As String)
                If Not Global.System.Object.Equals(Me._FirstName, value) Then
                    Me.RaiseDataMemberChanging("FirstName")
                    Me.ValidateProperty("FirstName", value)
                    Me._FirstName = value
                    Me.RaiseDataMemberChanged("FirstName")
                End If
            End Set
        End Property
        Private _FirstName As String
        
        <Global.System.Runtime.Serialization.DataMember()> _
        <Global.System.ComponentModel.DataAnnotations.RoundtripOriginal()> _
        Public Property LastName() As String Implements Global.LightSwitchApplication.Cleaner.DetailsClass.IImplementation.LastName
            Get
                Return Me._LastName
            End Get
            Set(ByVal value As String)
                If Not Global.System.Object.Equals(Me._LastName, value) Then
                    Me.RaiseDataMemberChanging("LastName")
                    Me.ValidateProperty("LastName", value)
                    Me._LastName = value
                    Me.RaiseDataMemberChanged("LastName")
                End If
            End Set
        End Property
        Private _LastName As String
        
        <Global.System.Runtime.Serialization.DataMember()> _
        <Global.System.ComponentModel.DataAnnotations.RoundtripOriginal()> _
        Public Property HourlyRate() As Decimal Implements Global.LightSwitchApplication.Cleaner.DetailsClass.IImplementation.HourlyRate
            Get
                Return Me._HourlyRate
            End Get
            Set(ByVal value As Decimal)
                If Not Global.System.Object.Equals(Me._HourlyRate, value) Then
                    Me.RaiseDataMemberChanging("HourlyRate")
                    Me.ValidateProperty("HourlyRate", value)
                    Me._HourlyRate = value
                    Me.RaiseDataMemberChanged("HourlyRate")
                End If
            End Set
        End Property
        Private _HourlyRate As Decimal
        
        <Global.System.Runtime.Serialization.DataMember()> _
        <Global.System.ComponentModel.DataAnnotations.RoundtripOriginal()> _
        Public Property StartDate() As Date Implements Global.LightSwitchApplication.Cleaner.DetailsClass.IImplementation.StartDate
            Get
                Return Me._StartDate
            End Get
            Set(ByVal value As Date)
                If Not Global.System.Object.Equals(Me._StartDate, value) Then
                    Me.RaiseDataMemberChanging("StartDate")
                    Me.ValidateProperty("StartDate", value)
                    Me._StartDate = value
                    Me.RaiseDataMemberChanged("StartDate")
                End If
            End Set
        End Property
        Private _StartDate As Date
        
        <Global.System.Runtime.Serialization.DataMember()> _
        <Global.System.ComponentModel.DataAnnotations.RoundtripOriginal()> _
        Public Property EndDate() As Global.System.Nullable(Of Date) Implements Global.LightSwitchApplication.Cleaner.DetailsClass.IImplementation.EndDate
            Get
                Return Me._EndDate
            End Get
            Set(ByVal value As Global.System.Nullable(Of Date))
                If Not Global.System.Object.Equals(Me._EndDate, value) Then
                    Me.RaiseDataMemberChanging("EndDate")
                    Me.ValidateProperty("EndDate", value)
                    Me._EndDate = value
                    Me.RaiseDataMemberChanged("EndDate")
                End If
            End Set
        End Property
        Private _EndDate As Global.System.Nullable(Of Date)
        
        <Global.System.Runtime.Serialization.DataMember()> _
        <Global.System.ComponentModel.DataAnnotations.RoundtripOriginal()> _
        Public Property Phone() As String Implements Global.LightSwitchApplication.Cleaner.DetailsClass.IImplementation.Phone
            Get
                Return Me._Phone
            End Get
            Set(ByVal value As String)
                If Not Global.System.Object.Equals(Me._Phone, value) Then
                    Me.RaiseDataMemberChanging("Phone")
                    Me.ValidateProperty("Phone", value)
                    Me._Phone = value
                    Me.RaiseDataMemberChanged("Phone")
                End If
            End Set
        End Property
        Private _Phone As String
        
        <Global.System.Runtime.Serialization.DataMember()> _
        <Global.System.ComponentModel.DataAnnotations.RoundtripOriginal()> _
        Public Property Email() As String Implements Global.LightSwitchApplication.Cleaner.DetailsClass.IImplementation.Email
            Get
                Return Me._Email
            End Get
            Set(ByVal value As String)
                If Not Global.System.Object.Equals(Me._Email, value) Then
                    Me.RaiseDataMemberChanging("Email")
                    Me.ValidateProperty("Email", value)
                    Me._Email = value
                    Me.RaiseDataMemberChanged("Email")
                End If
            End Set
        End Property
        Private _Email As String
        
        <Global.System.Runtime.Serialization.DataMember()> _
        <Global.System.ComponentModel.DataAnnotations.RoundtripOriginal()> _
        Public Property AddressLine1() As String Implements Global.LightSwitchApplication.Cleaner.DetailsClass.IImplementation.AddressLine1
            Get
                Return Me._AddressLine1
            End Get
            Set(ByVal value As String)
                If Not Global.System.Object.Equals(Me._AddressLine1, value) Then
                    Me.RaiseDataMemberChanging("AddressLine1")
                    Me.ValidateProperty("AddressLine1", value)
                    Me._AddressLine1 = value
                    Me.RaiseDataMemberChanged("AddressLine1")
                End If
            End Set
        End Property
        Private _AddressLine1 As String
        
        <Global.System.Runtime.Serialization.DataMember()> _
        <Global.System.ComponentModel.DataAnnotations.RoundtripOriginal()> _
        Public Property AddressLine2() As String Implements Global.LightSwitchApplication.Cleaner.DetailsClass.IImplementation.AddressLine2
            Get
                Return Me._AddressLine2
            End Get
            Set(ByVal value As String)
                If Not Global.System.Object.Equals(Me._AddressLine2, value) Then
                    Me.RaiseDataMemberChanging("AddressLine2")
                    Me.ValidateProperty("AddressLine2", value)
                    Me._AddressLine2 = value
                    Me.RaiseDataMemberChanged("AddressLine2")
                End If
            End Set
        End Property
        Private _AddressLine2 As String
        
        <Global.System.Runtime.Serialization.DataMember()> _
        <Global.System.ComponentModel.DataAnnotations.RoundtripOriginal()> _
        Public Property City() As String Implements Global.LightSwitchApplication.Cleaner.DetailsClass.IImplementation.City
            Get
                Return Me._City
            End Get
            Set(ByVal value As String)
                If Not Global.System.Object.Equals(Me._City, value) Then
                    Me.RaiseDataMemberChanging("City")
                    Me.ValidateProperty("City", value)
                    Me._City = value
                    Me.RaiseDataMemberChanged("City")
                End If
            End Set
        End Property
        Private _City As String
        
        <Global.System.Runtime.Serialization.DataMember()> _
        <Global.System.ComponentModel.DataAnnotations.RoundtripOriginal()> _
        Public Property Postcode() As String Implements Global.LightSwitchApplication.Cleaner.DetailsClass.IImplementation.Postcode
            Get
                Return Me._Postcode
            End Get
            Set(ByVal value As String)
                If Not Global.System.Object.Equals(Me._Postcode, value) Then
                    Me.RaiseDataMemberChanging("Postcode")
                    Me.ValidateProperty("Postcode", value)
                    Me._Postcode = value
                    Me.RaiseDataMemberChanged("Postcode")
                End If
            End Set
        End Property
        Private _Postcode As String
        
        <Global.System.Runtime.Serialization.DataMember()> _
        <Global.System.ComponentModel.DataAnnotations.RoundtripOriginal()> _
        Public Property CountryRegion() As String Implements Global.LightSwitchApplication.Cleaner.DetailsClass.IImplementation.CountryRegion
            Get
                Return Me._CountryRegion
            End Get
            Set(ByVal value As String)
                If Not Global.System.Object.Equals(Me._CountryRegion, value) Then
                    Me.RaiseDataMemberChanging("CountryRegion")
                    Me.ValidateProperty("CountryRegion", value)
                    Me._CountryRegion = value
                    Me.RaiseDataMemberChanged("CountryRegion")
                End If
            End Set
        End Property
        Private _CountryRegion As String
        
        <Global.System.ComponentModel.DataAnnotations.Association("Job_Cleaner", "Id", "Job_Cleaner")> _
        <Global.System.Xml.Serialization.XmlIgnore()> _
        Public ReadOnly Property Jobs() As Global.System.ServiceModel.DomainServices.Client.EntityCollection(Of Job)
            Get
                If (Me._Jobs Is Nothing) Then
                    Me._Jobs = New Global.System.ServiceModel.DomainServices.Client.EntityCollection(Of Global.LightSwitchApplication.Implementation.Job)(Me, "Jobs", AddressOf Me.FilterJobs, AddressOf Me.AttachJobs, AddressOf Me.DetachJobs)
                End If
                Return Me._Jobs
            End Get
        End Property
        Private _Jobs As Global.System.ServiceModel.DomainServices.Client.EntityCollection(Of Global.LightSwitchApplication.Implementation.Job)
        Private Sub AttachJobs(ByVal entity As Global.LightSwitchApplication.Implementation.Job)
            entity.Cleaner = Me
        End Sub
        Private Sub DetachJobs(ByVal entity As Global.LightSwitchApplication.Implementation.Job)
            entity.Cleaner = Nothing
        End Sub
        Private Function FilterJobs(ByVal entity As Global.LightSwitchApplication.Implementation.Job) As Boolean
            Return Global.System.Object.Equals(entity.Job_Cleaner, Me.Id)
        End Function
        Private ReadOnly Property _JobsImplementation() As Global.System.Collections.IEnumerable Implements Global.LightSwitchApplication.Cleaner.DetailsClass.IImplementation.Jobs
            Get
                Return Me.Jobs
            End Get
        End Property
        
        #Region "IEntityImplementation Members"
        Private __host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost
        
        Private ReadOnly Property __HostImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Host
            Get
                Return Me.__host
            End Get
        End Property
        
        Private Sub _Initialize(ByVal host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost) Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize
            Me.__host = host
        End Sub
        
        Protected Overrides Sub OnPropertyChanged(ByVal e As Global.System.ComponentModel.PropertyChangedEventArgs)
            MyBase.OnPropertyChanged(e)
        
            If Not Me.__host Is Nothing Then
                Me.__host.RaisePropertyChanged(e.PropertyName)
            End If
        End Sub
        #End Region
    End Class
    #End Region
    
    #Region "Client"
    <Global.System.Runtime.Serialization.DataContract(Namespace:="http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")> _
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public NotInheritable Class Client
        Inherits Global.System.ServiceModel.DomainServices.Client.Entity
        Implements Global.LightSwitchApplication.Client.DetailsClass.IImplementation
    
        Public Overrides Function GetIdentity() As Object
            If (Me.__host IsNot Nothing AndAlso Me.__host.IsNewlyAdded) Then
                Return Nothing
            End If
    
            Return Me._Id
        End Function
    
        <Global.System.ComponentModel.DataAnnotations.Key()> _
        <Global.System.ComponentModel.DataAnnotations.Editable(False, AllowInitialValue:=True)> _
        <Global.System.Runtime.Serialization.DataMember()> _
        <Global.System.ComponentModel.DataAnnotations.RoundtripOriginal()> _
        Public Property Id() As Integer Implements Global.LightSwitchApplication.Client.DetailsClass.IImplementation.Id
            Get
                Return Me._Id
            End Get
            Set(ByVal value As Integer)
                If Not Global.System.Object.Equals(Me._Id, value) Then
                    Me.ValidateProperty("Id", value)
                    Me._Id = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        Private _Id As Integer
        
        <Global.System.Runtime.Serialization.DataMember()> _
        <Global.System.ComponentModel.DataAnnotations.RoundtripOriginal()> _
        Public Property Name() As String Implements Global.LightSwitchApplication.Client.DetailsClass.IImplementation.Name
            Get
                Return Me._Name
            End Get
            Set(ByVal value As String)
                If Not Global.System.Object.Equals(Me._Name, value) Then
                    Me.RaiseDataMemberChanging("Name")
                    Me.ValidateProperty("Name", value)
                    Me._Name = value
                    Me.RaiseDataMemberChanged("Name")
                End If
            End Set
        End Property
        Private _Name As String
        
        <Global.System.Runtime.Serialization.DataMember()> _
        <Global.System.ComponentModel.DataAnnotations.RoundtripOriginal()> _
        Public Property Address1() As String Implements Global.LightSwitchApplication.Client.DetailsClass.IImplementation.Address1
            Get
                Return Me._Address1
            End Get
            Set(ByVal value As String)
                If Not Global.System.Object.Equals(Me._Address1, value) Then
                    Me.RaiseDataMemberChanging("Address1")
                    Me.ValidateProperty("Address1", value)
                    Me._Address1 = value
                    Me.RaiseDataMemberChanged("Address1")
                End If
            End Set
        End Property
        Private _Address1 As String
        
        <Global.System.Runtime.Serialization.DataMember()> _
        <Global.System.ComponentModel.DataAnnotations.RoundtripOriginal()> _
        Public Property Address2() As String Implements Global.LightSwitchApplication.Client.DetailsClass.IImplementation.Address2
            Get
                Return Me._Address2
            End Get
            Set(ByVal value As String)
                If Not Global.System.Object.Equals(Me._Address2, value) Then
                    Me.RaiseDataMemberChanging("Address2")
                    Me.ValidateProperty("Address2", value)
                    Me._Address2 = value
                    Me.RaiseDataMemberChanged("Address2")
                End If
            End Set
        End Property
        Private _Address2 As String
        
        <Global.System.Runtime.Serialization.DataMember()> _
        <Global.System.ComponentModel.DataAnnotations.RoundtripOriginal()> _
        Public Property City() As String Implements Global.LightSwitchApplication.Client.DetailsClass.IImplementation.City
            Get
                Return Me._City
            End Get
            Set(ByVal value As String)
                If Not Global.System.Object.Equals(Me._City, value) Then
                    Me.RaiseDataMemberChanging("City")
                    Me.ValidateProperty("City", value)
                    Me._City = value
                    Me.RaiseDataMemberChanged("City")
                End If
            End Set
        End Property
        Private _City As String
        
        <Global.System.Runtime.Serialization.DataMember()> _
        <Global.System.ComponentModel.DataAnnotations.RoundtripOriginal()> _
        Public Property Postcode() As String Implements Global.LightSwitchApplication.Client.DetailsClass.IImplementation.Postcode
            Get
                Return Me._Postcode
            End Get
            Set(ByVal value As String)
                If Not Global.System.Object.Equals(Me._Postcode, value) Then
                    Me.RaiseDataMemberChanging("Postcode")
                    Me.ValidateProperty("Postcode", value)
                    Me._Postcode = value
                    Me.RaiseDataMemberChanged("Postcode")
                End If
            End Set
        End Property
        Private _Postcode As String
        
        <Global.System.Runtime.Serialization.DataMember()> _
        <Global.System.ComponentModel.DataAnnotations.RoundtripOriginal()> _
        Public Property Region() As String Implements Global.LightSwitchApplication.Client.DetailsClass.IImplementation.Region
            Get
                Return Me._Region
            End Get
            Set(ByVal value As String)
                If Not Global.System.Object.Equals(Me._Region, value) Then
                    Me.RaiseDataMemberChanging("Region")
                    Me.ValidateProperty("Region", value)
                    Me._Region = value
                    Me.RaiseDataMemberChanged("Region")
                End If
            End Set
        End Property
        Private _Region As String
        
        <Global.System.Runtime.Serialization.DataMember()> _
        <Global.System.ComponentModel.DataAnnotations.RoundtripOriginal()> _
        Public Property Phone() As String Implements Global.LightSwitchApplication.Client.DetailsClass.IImplementation.Phone
            Get
                Return Me._Phone
            End Get
            Set(ByVal value As String)
                If Not Global.System.Object.Equals(Me._Phone, value) Then
                    Me.RaiseDataMemberChanging("Phone")
                    Me.ValidateProperty("Phone", value)
                    Me._Phone = value
                    Me.RaiseDataMemberChanged("Phone")
                End If
            End Set
        End Property
        Private _Phone As String
        
        <Global.System.Runtime.Serialization.DataMember()> _
        <Global.System.ComponentModel.DataAnnotations.RoundtripOriginal()> _
        Public Property Email() As String Implements Global.LightSwitchApplication.Client.DetailsClass.IImplementation.Email
            Get
                Return Me._Email
            End Get
            Set(ByVal value As String)
                If Not Global.System.Object.Equals(Me._Email, value) Then
                    Me.RaiseDataMemberChanging("Email")
                    Me.ValidateProperty("Email", value)
                    Me._Email = value
                    Me.RaiseDataMemberChanged("Email")
                End If
            End Set
        End Property
        Private _Email As String
        
        <Global.System.Runtime.Serialization.DataMember()> _
        <Global.System.ComponentModel.DataAnnotations.RoundtripOriginal()> _
        Public Property QueryString() As String Implements Global.LightSwitchApplication.Client.DetailsClass.IImplementation.QueryString
            Get
                Return Me._QueryString
            End Get
            Set(ByVal value As String)
                If Not Global.System.Object.Equals(Me._QueryString, value) Then
                    Me.RaiseDataMemberChanging("QueryString")
                    Me.ValidateProperty("QueryString", value)
                    Me._QueryString = value
                    Me.RaiseDataMemberChanged("QueryString")
                End If
            End Set
        End Property
        Private _QueryString As String
        
        <Global.System.ComponentModel.DataAnnotations.Association("Job_Client", "Id", "Job_Client")> _
        <Global.System.Xml.Serialization.XmlIgnore()> _
        Public ReadOnly Property Jobs() As Global.System.ServiceModel.DomainServices.Client.EntityCollection(Of Job)
            Get
                If (Me._Jobs Is Nothing) Then
                    Me._Jobs = New Global.System.ServiceModel.DomainServices.Client.EntityCollection(Of Global.LightSwitchApplication.Implementation.Job)(Me, "Jobs", AddressOf Me.FilterJobs, AddressOf Me.AttachJobs, AddressOf Me.DetachJobs)
                End If
                Return Me._Jobs
            End Get
        End Property
        Private _Jobs As Global.System.ServiceModel.DomainServices.Client.EntityCollection(Of Global.LightSwitchApplication.Implementation.Job)
        Private Sub AttachJobs(ByVal entity As Global.LightSwitchApplication.Implementation.Job)
            entity.Client = Me
        End Sub
        Private Sub DetachJobs(ByVal entity As Global.LightSwitchApplication.Implementation.Job)
            entity.Client = Nothing
        End Sub
        Private Function FilterJobs(ByVal entity As Global.LightSwitchApplication.Implementation.Job) As Boolean
            Return Global.System.Object.Equals(entity.Job_Client, Me.Id)
        End Function
        Private ReadOnly Property _JobsImplementation() As Global.System.Collections.IEnumerable Implements Global.LightSwitchApplication.Client.DetailsClass.IImplementation.Jobs
            Get
                Return Me.Jobs
            End Get
        End Property
        
        #Region "IEntityImplementation Members"
        Private __host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost
        
        Private ReadOnly Property __HostImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Host
            Get
                Return Me.__host
            End Get
        End Property
        
        Private Sub _Initialize(ByVal host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost) Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize
            Me.__host = host
        End Sub
        
        Protected Overrides Sub OnPropertyChanged(ByVal e As Global.System.ComponentModel.PropertyChangedEventArgs)
            MyBase.OnPropertyChanged(e)
        
            If Not Me.__host Is Nothing Then
                Me.__host.RaisePropertyChanged(e.PropertyName)
            End If
        End Sub
        #End Region
    End Class
    #End Region
    
    #Region "Job"
    <Global.System.Runtime.Serialization.DataContract(Namespace:="http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")> _
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public NotInheritable Class Job
        Inherits Global.System.ServiceModel.DomainServices.Client.Entity
        Implements Global.LightSwitchApplication.Job.DetailsClass.IImplementation
    
        Public Overrides Function GetIdentity() As Object
            If (Me.__host IsNot Nothing AndAlso Me.__host.IsNewlyAdded) Then
                Return Nothing
            End If
    
            Return Me._Id
        End Function
    
        <Global.System.ComponentModel.DataAnnotations.Key()> _
        <Global.System.ComponentModel.DataAnnotations.Editable(False, AllowInitialValue:=True)> _
        <Global.System.Runtime.Serialization.DataMember()> _
        <Global.System.ComponentModel.DataAnnotations.RoundtripOriginal()> _
        Public Property Id() As Integer Implements Global.LightSwitchApplication.Job.DetailsClass.IImplementation.Id
            Get
                Return Me._Id
            End Get
            Set(ByVal value As Integer)
                If Not Global.System.Object.Equals(Me._Id, value) Then
                    Me.ValidateProperty("Id", value)
                    Me._Id = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        Private _Id As Integer
        
        <Global.System.Runtime.Serialization.DataMember()> _
        <Global.System.ComponentModel.DataAnnotations.RoundtripOriginal()> _
        Public Property StartTime() As Date Implements Global.LightSwitchApplication.Job.DetailsClass.IImplementation.StartTime
            Get
                Return Me._StartTime
            End Get
            Set(ByVal value As Date)
                If Not Global.System.Object.Equals(Me._StartTime, value) Then
                    Me.RaiseDataMemberChanging("StartTime")
                    Me.ValidateProperty("StartTime", value)
                    Me._StartTime = value
                    Me.RaiseDataMemberChanged("StartTime")
                End If
            End Set
        End Property
        Private _StartTime As Date
        
        <Global.System.Runtime.Serialization.DataMember()> _
        <Global.System.ComponentModel.DataAnnotations.RoundtripOriginal()> _
        Public Property EndTime() As Date Implements Global.LightSwitchApplication.Job.DetailsClass.IImplementation.EndTime
            Get
                Return Me._EndTime
            End Get
            Set(ByVal value As Date)
                If Not Global.System.Object.Equals(Me._EndTime, value) Then
                    Me.RaiseDataMemberChanging("EndTime")
                    Me.ValidateProperty("EndTime", value)
                    Me._EndTime = value
                    Me.RaiseDataMemberChanged("EndTime")
                End If
            End Set
        End Property
        Private _EndTime As Date
        
        <Global.System.Runtime.Serialization.DataMember()> _
        <Global.System.ComponentModel.DataAnnotations.RoundtripOriginal()> _
        Public Property Price() As Decimal Implements Global.LightSwitchApplication.Job.DetailsClass.IImplementation.Price
            Get
                Return Me._Price
            End Get
            Set(ByVal value As Decimal)
                If Not Global.System.Object.Equals(Me._Price, value) Then
                    Me.RaiseDataMemberChanging("Price")
                    Me.ValidateProperty("Price", value)
                    Me._Price = value
                    Me.RaiseDataMemberChanged("Price")
                End If
            End Set
        End Property
        Private _Price As Decimal
        
        <Global.System.Runtime.Serialization.DataMember()> _
        <Global.System.ComponentModel.DataAnnotations.RoundtripOriginal()> _
        Public Property CleanersRate() As Decimal Implements Global.LightSwitchApplication.Job.DetailsClass.IImplementation.CleanersRate
            Get
                Return Me._CleanersRate
            End Get
            Set(ByVal value As Decimal)
                If Not Global.System.Object.Equals(Me._CleanersRate, value) Then
                    Me.RaiseDataMemberChanging("CleanersRate")
                    Me.ValidateProperty("CleanersRate", value)
                    Me._CleanersRate = value
                    Me.RaiseDataMemberChanged("CleanersRate")
                End If
            End Set
        End Property
        Private _CleanersRate As Decimal
        
        <Global.System.Runtime.Serialization.DataMember()> _
        <Global.System.ComponentModel.DataAnnotations.RoundtripOriginal()> _
        Public Property PerPeriod() As String Implements Global.LightSwitchApplication.Job.DetailsClass.IImplementation.PerPeriod
            Get
                Return Me._PerPeriod
            End Get
            Set(ByVal value As String)
                If Not Global.System.Object.Equals(Me._PerPeriod, value) Then
                    Me.RaiseDataMemberChanging("PerPeriod")
                    Me.ValidateProperty("PerPeriod", value)
                    Me._PerPeriod = value
                    Me.RaiseDataMemberChanged("PerPeriod")
                End If
            End Set
        End Property
        Private _PerPeriod As String
        
        <Global.System.Runtime.Serialization.DataMember()> _
        <Global.System.ComponentModel.DataAnnotations.RoundtripOriginal()> _
        Public Property Recurance() As String Implements Global.LightSwitchApplication.Job.DetailsClass.IImplementation.Recurance
            Get
                Return Me._Recurance
            End Get
            Set(ByVal value As String)
                If Not Global.System.Object.Equals(Me._Recurance, value) Then
                    Me.RaiseDataMemberChanging("Recurance")
                    Me.ValidateProperty("Recurance", value)
                    Me._Recurance = value
                    Me.RaiseDataMemberChanged("Recurance")
                End If
            End Set
        End Property
        Private _Recurance As String
        
        <Global.System.Runtime.Serialization.DataMember()> _
        <Global.System.ComponentModel.DataAnnotations.RoundtripOriginal()> _
        Public Property Note() As String Implements Global.LightSwitchApplication.Job.DetailsClass.IImplementation.Note
            Get
                Return Me._Note
            End Get
            Set(ByVal value As String)
                If Not Global.System.Object.Equals(Me._Note, value) Then
                    Me.RaiseDataMemberChanging("Note")
                    Me.ValidateProperty("Note", value)
                    Me._Note = value
                    Me.RaiseDataMemberChanged("Note")
                End If
            End Set
        End Property
        Private _Note As String
        
        <Global.System.Runtime.Serialization.DataMember()> _
        <Global.System.ComponentModel.DataAnnotations.RoundtripOriginal()> _
        Public Property QueryString() As String Implements Global.LightSwitchApplication.Job.DetailsClass.IImplementation.QueryString
            Get
                Return Me._QueryString
            End Get
            Set(ByVal value As String)
                If Not Global.System.Object.Equals(Me._QueryString, value) Then
                    Me.RaiseDataMemberChanging("QueryString")
                    Me.ValidateProperty("QueryString", value)
                    Me._QueryString = value
                    Me.RaiseDataMemberChanged("QueryString")
                End If
            End Set
        End Property
        Private _QueryString As String
        
        <Global.System.Runtime.Serialization.DataMember()> _
        <Global.System.ComponentModel.DataAnnotations.RoundtripOriginal()> _
        Public Property IsDeleted() As Boolean Implements Global.LightSwitchApplication.Job.DetailsClass.IImplementation.IsDeleted
            Get
                Return Me._IsDeleted
            End Get
            Set(ByVal value As Boolean)
                If Not Global.System.Object.Equals(Me._IsDeleted, value) Then
                    Me.RaiseDataMemberChanging("IsDeleted")
                    Me.ValidateProperty("IsDeleted", value)
                    Me._IsDeleted = value
                    Me.RaiseDataMemberChanged("IsDeleted")
                End If
            End Set
        End Property
        Private _IsDeleted As Boolean
        
        <Global.System.Runtime.Serialization.DataMember()> _
        <Global.System.ComponentModel.DataAnnotations.RoundtripOriginal()> _
        Public Property StreetAddress1() As String Implements Global.LightSwitchApplication.Job.DetailsClass.IImplementation.StreetAddress1
            Get
                Return Me._StreetAddress1
            End Get
            Set(ByVal value As String)
                If Not Global.System.Object.Equals(Me._StreetAddress1, value) Then
                    Me.RaiseDataMemberChanging("StreetAddress1")
                    Me.ValidateProperty("StreetAddress1", value)
                    Me._StreetAddress1 = value
                    Me.RaiseDataMemberChanged("StreetAddress1")
                End If
            End Set
        End Property
        Private _StreetAddress1 As String
        
        <Global.System.Runtime.Serialization.DataMember()> _
        <Global.System.ComponentModel.DataAnnotations.RoundtripOriginal()> _
        Public Property StreetAddress2() As String Implements Global.LightSwitchApplication.Job.DetailsClass.IImplementation.StreetAddress2
            Get
                Return Me._StreetAddress2
            End Get
            Set(ByVal value As String)
                If Not Global.System.Object.Equals(Me._StreetAddress2, value) Then
                    Me.RaiseDataMemberChanging("StreetAddress2")
                    Me.ValidateProperty("StreetAddress2", value)
                    Me._StreetAddress2 = value
                    Me.RaiseDataMemberChanged("StreetAddress2")
                End If
            End Set
        End Property
        Private _StreetAddress2 As String
        
        <Global.System.Runtime.Serialization.DataMember()> _
        <Global.System.ComponentModel.DataAnnotations.RoundtripOriginal()> _
        Public Property City() As String Implements Global.LightSwitchApplication.Job.DetailsClass.IImplementation.City
            Get
                Return Me._City
            End Get
            Set(ByVal value As String)
                If Not Global.System.Object.Equals(Me._City, value) Then
                    Me.RaiseDataMemberChanging("City")
                    Me.ValidateProperty("City", value)
                    Me._City = value
                    Me.RaiseDataMemberChanged("City")
                End If
            End Set
        End Property
        Private _City As String
        
        <Global.System.Runtime.Serialization.DataMember()> _
        <Global.System.ComponentModel.DataAnnotations.RoundtripOriginal()> _
        Public Property Postcode() As String Implements Global.LightSwitchApplication.Job.DetailsClass.IImplementation.Postcode
            Get
                Return Me._Postcode
            End Get
            Set(ByVal value As String)
                If Not Global.System.Object.Equals(Me._Postcode, value) Then
                    Me.RaiseDataMemberChanging("Postcode")
                    Me.ValidateProperty("Postcode", value)
                    Me._Postcode = value
                    Me.RaiseDataMemberChanged("Postcode")
                End If
            End Set
        End Property
        Private _Postcode As String
        
        <Global.System.Runtime.Serialization.DataMember()> _
        <Global.System.ComponentModel.DataAnnotations.RoundtripOriginal()> _
        Public Property Job_Cleaner() As Global.System.Nullable(Of Integer)
            Get
                Return Me._Job_Cleaner
            End Get
            Set(ByVal value As Global.System.Nullable(Of Integer))
                If Not Global.System.Object.Equals(Me._Job_Cleaner, value) Then
                    Me.RaiseDataMemberChanging("Job_Cleaner")
                    Me.ValidateProperty("Job_Cleaner", value)
                    Me._Job_Cleaner = value
                    Me.RaiseDataMemberChanged("Job_Cleaner")
                End If
            End Set
        End Property
        Private _Job_Cleaner As Global.System.Nullable(Of Integer)
        
        <Global.System.ComponentModel.DataAnnotations.Association("Job_Cleaner", "Job_Cleaner", "Id", IsForeignKey:=True)> _
        <Global.System.Xml.Serialization.XmlIgnore()> _
        Public Property Cleaner() As Global.LightSwitchApplication.Implementation.Cleaner
            Get
                If (Me._Cleaner Is Nothing) Then
                    Me._Cleaner = New Global.System.ServiceModel.DomainServices.Client.EntityRef(Of Global.LightSwitchApplication.Implementation.Cleaner)(Me, "Cleaner", AddressOf Me.FilterCleaner)
                End If
                Return Me._Cleaner.Entity
            End Get
            Set(ByVal value As Global.LightSwitchApplication.Implementation.Cleaner)
                Dim previous As Cleaner = Me.Cleaner
                If (previous IsNot value) Then
                    Me.ValidateProperty("Cleaner", value)
                    If (previous IsNot Nothing) Then
                        Me._Cleaner.Entity = Nothing
                        previous.Jobs.Remove(Me)
                    End If
                    If (value IsNot Nothing) Then
                        Me.Job_Cleaner = value.Id
                    Else
                        Me.Job_Cleaner = Nothing
                    End If
                    Me._Cleaner.Entity = value
                    If (value IsNot Nothing) Then
                        value.Jobs.Add(Me)
                    End If
                    Me.RaisePropertyChanged("Cleaner")
                End If
            End Set
        End Property
        Private _Cleaner As Global.System.ServiceModel.DomainServices.Client.EntityRef(Of Global.LightSwitchApplication.Implementation.Cleaner)
        Private Function FilterCleaner(ByVal entity As Global.LightSwitchApplication.Implementation.Cleaner) As Boolean
            Return Global.System.Object.Equals(entity.Id, Me.Job_Cleaner)
        End Function
        Private Property _CleanerImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementation Implements Global.LightSwitchApplication.Job.DetailsClass.IImplementation.Cleaner
            Get
                Return Me.Cleaner
            End Get
            Set(ByVal value As Global.Microsoft.LightSwitch.Internal.IEntityImplementation)
                Me.Cleaner = DirectCast(value, Global.LightSwitchApplication.Implementation.Cleaner)
            End Set
        End Property
        
        <Global.System.Runtime.Serialization.DataMember()> _
        <Global.System.ComponentModel.DataAnnotations.RoundtripOriginal()> _
        Public Property Job_Client() As Integer
            Get
                Return Me._Job_Client
            End Get
            Set(ByVal value As Integer)
                If Not Global.System.Object.Equals(Me._Job_Client, value) Then
                    Me.RaiseDataMemberChanging("Job_Client")
                    Me.ValidateProperty("Job_Client", value)
                    Me._Job_Client = value
                    Me.RaiseDataMemberChanged("Job_Client")
                End If
            End Set
        End Property
        Private _Job_Client As Integer
        
        <Global.System.ComponentModel.DataAnnotations.Association("Job_Client", "Job_Client", "Id", IsForeignKey:=True)> _
        <Global.System.Xml.Serialization.XmlIgnore()> _
        Public Property Client() As Global.LightSwitchApplication.Implementation.Client
            Get
                If (Me._Client Is Nothing) Then
                    Me._Client = New Global.System.ServiceModel.DomainServices.Client.EntityRef(Of Global.LightSwitchApplication.Implementation.Client)(Me, "Client", AddressOf Me.FilterClient)
                End If
                Return Me._Client.Entity
            End Get
            Set(ByVal value As Global.LightSwitchApplication.Implementation.Client)
                Dim previous As Client = Me.Client
                If (previous IsNot value) Then
                    Me.ValidateProperty("Client", value)
                    If (previous IsNot Nothing) Then
                        Me._Client.Entity = Nothing
                        previous.Jobs.Remove(Me)
                    End If
                    If (value IsNot Nothing) Then
                        Me.Job_Client = value.Id
                    Else
                        Me.Job_Client = Nothing
                    End If
                    Me._Client.Entity = value
                    If (value IsNot Nothing) Then
                        value.Jobs.Add(Me)
                    End If
                    Me.RaisePropertyChanged("Client")
                End If
            End Set
        End Property
        Private _Client As Global.System.ServiceModel.DomainServices.Client.EntityRef(Of Global.LightSwitchApplication.Implementation.Client)
        Private Function FilterClient(ByVal entity As Global.LightSwitchApplication.Implementation.Client) As Boolean
            Return Global.System.Object.Equals(entity.Id, Me.Job_Client)
        End Function
        Private Property _ClientImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementation Implements Global.LightSwitchApplication.Job.DetailsClass.IImplementation.Client
            Get
                Return Me.Client
            End Get
            Set(ByVal value As Global.Microsoft.LightSwitch.Internal.IEntityImplementation)
                Me.Client = DirectCast(value, Global.LightSwitchApplication.Implementation.Client)
            End Set
        End Property
        
        #Region "IEntityImplementation Members"
        Private __host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost
        
        Private ReadOnly Property __HostImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Host
            Get
                Return Me.__host
            End Get
        End Property
        
        Private Sub _Initialize(ByVal host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost) Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize
            Me.__host = host
        End Sub
        
        Protected Overrides Sub OnPropertyChanged(ByVal e As Global.System.ComponentModel.PropertyChangedEventArgs)
            MyBase.OnPropertyChanged(e)
        
            If Not Me.__host Is Nothing Then
                Me.__host.RaisePropertyChanged(e.PropertyName)
            End If
        End Sub
        #End Region
    End Class
    #End Region
    
    #Region "ApplicationData"
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public Class ApplicationData
        Inherits Global.Microsoft.LightSwitch.ClientGenerated.Implementation.DomainContext
    
        Public Sub New(ByVal dataService As Global.Microsoft.LightSwitch.IDataService)
            MyBase.New(dataService, Global.Microsoft.LightSwitch.ClientGenerated.Implementation.DomainContext.CreateWcfDomainClient(Of IApplicationDataContract)(New Global.System.Uri("LightSwitchApplication-Implementation-ApplicationDataDomainService.svc", Global.System.UriKind.Relative)))
        End Sub
    
        Public ReadOnly Property CleanerEntityList() As Global.System.ServiceModel.DomainServices.Client.EntitySet(Of Global.LightSwitchApplication.Implementation.Cleaner)
            Get
                Return MyBase.EntityContainer.GetEntitySet(Of Global.LightSwitchApplication.Implementation.Cleaner)()
            End Get
        End Property
        Public ReadOnly Property ClientEntityList() As Global.System.ServiceModel.DomainServices.Client.EntitySet(Of Global.LightSwitchApplication.Implementation.Client)
            Get
                Return MyBase.EntityContainer.GetEntitySet(Of Global.LightSwitchApplication.Implementation.Client)()
            End Get
        End Property
        Public ReadOnly Property JobEntityList() As Global.System.ServiceModel.DomainServices.Client.EntitySet(Of Global.LightSwitchApplication.Implementation.Job)
            Get
                Return MyBase.EntityContainer.GetEntitySet(Of Global.LightSwitchApplication.Implementation.Job)()
            End Get
        End Property
        Protected Overrides Function CreateEntityContainer() As Global.System.ServiceModel.DomainServices.Client.EntityContainer
            Return New ApplicationDataEntityContainer
        End Function
    
        Friend NotInheritable Class ApplicationDataEntityContainer
            Inherits Global.System.ServiceModel.DomainServices.Client.EntityContainer
            Public Sub New()
                Me.CreateEntitySet(Of Global.LightSwitchApplication.Implementation.Cleaner)(Global.System.ServiceModel.DomainServices.Client.EntitySetOperations.All)
                Me.CreateEntitySet(Of Global.LightSwitchApplication.Implementation.Client)(Global.System.ServiceModel.DomainServices.Client.EntitySetOperations.All)
                Me.CreateEntitySet(Of Global.LightSwitchApplication.Implementation.Job)(Global.System.ServiceModel.DomainServices.Client.EntitySetOperations.All)
            End Sub
        End Class
    
        #Region "Service Contract Interface"
    
        <Global.System.ServiceModel.ServiceContract> _
        Public Interface IApplicationDataContract
            <Global.System.ServiceModel.OperationContract(AsyncPattern:=True, Action:="http://tempuri.org/ApplicationDataDomainService/Cleaners_Single", ReplyAction:="http://tempuri.org/ApplicationDataDomainService/Cleaners_SingleResponse"),
             Global.System.ServiceModel.Web.WebGet(),
             Global.System.ServiceModel.FaultContract(GetType(Global.System.ServiceModel.DomainServices.Client.DomainServiceFault), Action:="http://tempuri.org/ApplicationDataDomainService/Cleaners_SingleDomainServiceFault", Name:="DomainServiceFault", Namespace:="DomainServices")> _
            Function BeginCleaners_Single(ByVal frameworkOperators as String, ByVal Id As Global.System.Nullable(Of Integer), ByVal callback As Global.System.AsyncCallback, ByVal asyncState As Global.System.Object) As Global.System.IAsyncResult
            Function EndCleaners_Single(ByVal result As Global.System.IAsyncResult) As Global.System.ServiceModel.DomainServices.Client.QueryResult(Of Global.LightSwitchApplication.Implementation.Cleaner)
            
            <Global.System.ServiceModel.OperationContract(AsyncPattern:=True, Action:="http://tempuri.org/ApplicationDataDomainService/Cleaners_SingleOrDefault", ReplyAction:="http://tempuri.org/ApplicationDataDomainService/Cleaners_SingleOrDefaultResponse"),
             Global.System.ServiceModel.Web.WebGet(),
             Global.System.ServiceModel.FaultContract(GetType(Global.System.ServiceModel.DomainServices.Client.DomainServiceFault), Action:="http://tempuri.org/ApplicationDataDomainService/Cleaners_SingleOrDefaultDomainServiceFault", Name:="DomainServiceFault", Namespace:="DomainServices")> _
            Function BeginCleaners_SingleOrDefault(ByVal frameworkOperators as String, ByVal Id As Global.System.Nullable(Of Integer), ByVal callback As Global.System.AsyncCallback, ByVal asyncState As Global.System.Object) As Global.System.IAsyncResult
            Function EndCleaners_SingleOrDefault(ByVal result As Global.System.IAsyncResult) As Global.System.ServiceModel.DomainServices.Client.QueryResult(Of Global.LightSwitchApplication.Implementation.Cleaner)
            
            <Global.System.ServiceModel.OperationContract(AsyncPattern:=True, Action:="http://tempuri.org/ApplicationDataDomainService/Cleaners_All", ReplyAction:="http://tempuri.org/ApplicationDataDomainService/Cleaners_AllResponse"),
             Global.System.ServiceModel.Web.WebGet(),
             Global.System.ServiceModel.FaultContract(GetType(Global.System.ServiceModel.DomainServices.Client.DomainServiceFault), Action:="http://tempuri.org/ApplicationDataDomainService/Cleaners_AllDomainServiceFault", Name:="DomainServiceFault", Namespace:="DomainServices")> _
            Function BeginCleaners_All(ByVal frameworkOperators as String, ByVal callback As Global.System.AsyncCallback, ByVal asyncState As Global.System.Object) As Global.System.IAsyncResult
            Function EndCleaners_All(ByVal result As Global.System.IAsyncResult) As Global.System.ServiceModel.DomainServices.Client.QueryResult(Of Global.LightSwitchApplication.Implementation.Cleaner)
            
            <Global.System.ServiceModel.OperationContract(AsyncPattern:=True, Action:="http://tempuri.org/ApplicationDataDomainService/Clients_Single", ReplyAction:="http://tempuri.org/ApplicationDataDomainService/Clients_SingleResponse"),
             Global.System.ServiceModel.Web.WebGet(),
             Global.System.ServiceModel.FaultContract(GetType(Global.System.ServiceModel.DomainServices.Client.DomainServiceFault), Action:="http://tempuri.org/ApplicationDataDomainService/Clients_SingleDomainServiceFault", Name:="DomainServiceFault", Namespace:="DomainServices")> _
            Function BeginClients_Single(ByVal frameworkOperators as String, ByVal Id As Global.System.Nullable(Of Integer), ByVal callback As Global.System.AsyncCallback, ByVal asyncState As Global.System.Object) As Global.System.IAsyncResult
            Function EndClients_Single(ByVal result As Global.System.IAsyncResult) As Global.System.ServiceModel.DomainServices.Client.QueryResult(Of Global.LightSwitchApplication.Implementation.Client)
            
            <Global.System.ServiceModel.OperationContract(AsyncPattern:=True, Action:="http://tempuri.org/ApplicationDataDomainService/Clients_SingleOrDefault", ReplyAction:="http://tempuri.org/ApplicationDataDomainService/Clients_SingleOrDefaultResponse"),
             Global.System.ServiceModel.Web.WebGet(),
             Global.System.ServiceModel.FaultContract(GetType(Global.System.ServiceModel.DomainServices.Client.DomainServiceFault), Action:="http://tempuri.org/ApplicationDataDomainService/Clients_SingleOrDefaultDomainServiceFault", Name:="DomainServiceFault", Namespace:="DomainServices")> _
            Function BeginClients_SingleOrDefault(ByVal frameworkOperators as String, ByVal Id As Global.System.Nullable(Of Integer), ByVal callback As Global.System.AsyncCallback, ByVal asyncState As Global.System.Object) As Global.System.IAsyncResult
            Function EndClients_SingleOrDefault(ByVal result As Global.System.IAsyncResult) As Global.System.ServiceModel.DomainServices.Client.QueryResult(Of Global.LightSwitchApplication.Implementation.Client)
            
            <Global.System.ServiceModel.OperationContract(AsyncPattern:=True, Action:="http://tempuri.org/ApplicationDataDomainService/Clients_All", ReplyAction:="http://tempuri.org/ApplicationDataDomainService/Clients_AllResponse"),
             Global.System.ServiceModel.Web.WebGet(),
             Global.System.ServiceModel.FaultContract(GetType(Global.System.ServiceModel.DomainServices.Client.DomainServiceFault), Action:="http://tempuri.org/ApplicationDataDomainService/Clients_AllDomainServiceFault", Name:="DomainServiceFault", Namespace:="DomainServices")> _
            Function BeginClients_All(ByVal frameworkOperators as String, ByVal callback As Global.System.AsyncCallback, ByVal asyncState As Global.System.Object) As Global.System.IAsyncResult
            Function EndClients_All(ByVal result As Global.System.IAsyncResult) As Global.System.ServiceModel.DomainServices.Client.QueryResult(Of Global.LightSwitchApplication.Implementation.Client)
            
            <Global.System.ServiceModel.OperationContract(AsyncPattern:=True, Action:="http://tempuri.org/ApplicationDataDomainService/Jobs_Single", ReplyAction:="http://tempuri.org/ApplicationDataDomainService/Jobs_SingleResponse"),
             Global.System.ServiceModel.Web.WebGet(),
             Global.System.ServiceModel.FaultContract(GetType(Global.System.ServiceModel.DomainServices.Client.DomainServiceFault), Action:="http://tempuri.org/ApplicationDataDomainService/Jobs_SingleDomainServiceFault", Name:="DomainServiceFault", Namespace:="DomainServices")> _
            Function BeginJobs_Single(ByVal frameworkOperators as String, ByVal Id As Global.System.Nullable(Of Integer), ByVal callback As Global.System.AsyncCallback, ByVal asyncState As Global.System.Object) As Global.System.IAsyncResult
            Function EndJobs_Single(ByVal result As Global.System.IAsyncResult) As Global.System.ServiceModel.DomainServices.Client.QueryResult(Of Global.LightSwitchApplication.Implementation.Job)
            
            <Global.System.ServiceModel.OperationContract(AsyncPattern:=True, Action:="http://tempuri.org/ApplicationDataDomainService/Jobs_SingleOrDefault", ReplyAction:="http://tempuri.org/ApplicationDataDomainService/Jobs_SingleOrDefaultResponse"),
             Global.System.ServiceModel.Web.WebGet(),
             Global.System.ServiceModel.FaultContract(GetType(Global.System.ServiceModel.DomainServices.Client.DomainServiceFault), Action:="http://tempuri.org/ApplicationDataDomainService/Jobs_SingleOrDefaultDomainServiceFault", Name:="DomainServiceFault", Namespace:="DomainServices")> _
            Function BeginJobs_SingleOrDefault(ByVal frameworkOperators as String, ByVal Id As Global.System.Nullable(Of Integer), ByVal callback As Global.System.AsyncCallback, ByVal asyncState As Global.System.Object) As Global.System.IAsyncResult
            Function EndJobs_SingleOrDefault(ByVal result As Global.System.IAsyncResult) As Global.System.ServiceModel.DomainServices.Client.QueryResult(Of Global.LightSwitchApplication.Implementation.Job)
            
            <Global.System.ServiceModel.OperationContract(AsyncPattern:=True, Action:="http://tempuri.org/ApplicationDataDomainService/Jobs_All", ReplyAction:="http://tempuri.org/ApplicationDataDomainService/Jobs_AllResponse"),
             Global.System.ServiceModel.Web.WebGet(),
             Global.System.ServiceModel.FaultContract(GetType(Global.System.ServiceModel.DomainServices.Client.DomainServiceFault), Action:="http://tempuri.org/ApplicationDataDomainService/Jobs_AllDomainServiceFault", Name:="DomainServiceFault", Namespace:="DomainServices")> _
            Function BeginJobs_All(ByVal frameworkOperators as String, ByVal callback As Global.System.AsyncCallback, ByVal asyncState As Global.System.Object) As Global.System.IAsyncResult
            Function EndJobs_All(ByVal result As Global.System.IAsyncResult) As Global.System.ServiceModel.DomainServices.Client.QueryResult(Of Global.LightSwitchApplication.Implementation.Job)
            
            <Global.System.ServiceModel.OperationContract(AsyncPattern:=True, Action:="http://tempuri.org/ApplicationDataDomainService/SubmitChanges", ReplyAction:="http://tempuri.org/ApplicationDataDomainService/SubmitChangesResponse"),
             Global.System.ServiceModel.FaultContract(GetType(Global.System.ServiceModel.DomainServices.Client.DomainServiceFault), Action:="http://tempuri.org/ApplicationDataDomainService/SubmitChangesDomainServiceFault", Name:="DomainServiceFault", Namespace:="DomainServices")> _
            Function BeginSubmitChanges(ByVal changeSet As Global.System.Collections.Generic.IEnumerable(Of Global.System.ServiceModel.DomainServices.Client.ChangeSetEntry), ByVal callback As Global.System.AsyncCallback, ByVal asyncState As Global.System.Object) As Global.System.IAsyncResult
            Function EndSubmitChanges(ByVal result As Global.System.IAsyncResult) As Global.System.Collections.Generic.IEnumerable(Of Global.System.ServiceModel.DomainServices.Client.ChangeSetEntry)
            
            <Global.System.ServiceModel.OperationContract(AsyncPattern:=True, Action:="http://tempuri.org/ApplicationDataDomainService/__GetEntitySetCanInformation", ReplyAction:="http://tempuri.org/ApplicationDataDomainService/__GetEntitySetCanInformationResponse"),
             Global.System.ServiceModel.Web.WebGet(),
             Global.System.ServiceModel.FaultContract(GetType(Global.System.ServiceModel.DomainServices.Client.DomainServiceFault), Action:="http://tempuri.org/ApplicationDataDomainService/__GetEntitySetCanInformationDomainServiceFault", Name:="DomainServiceFault", Namespace:="DomainServices")> _
            Function Begin__GetEntitySetCanInformation(ByVal entitySetName As String, ByVal callback As Global.System.AsyncCallback, ByVal asyncState As Global.System.Object) As Global.System.IAsyncResult
            Function End__GetEntitySetCanInformation(ByVal result As Global.System.IAsyncResult) As Integer
            
            <Global.System.ServiceModel.OperationContract(AsyncPattern:=True, Action:="http://tempuri.org/ApplicationDataDomainService/__CanExecuteOperation", ReplyAction:="http://tempuri.org/ApplicationDataDomainService/__CanExecuteOperationResponse"),
             Global.System.ServiceModel.Web.WebGet(),
             Global.System.ServiceModel.FaultContract(GetType(Global.System.ServiceModel.DomainServices.Client.DomainServiceFault), Action:="http://tempuri.org/ApplicationDataDomainService/__CanExecuteOperationDomainServiceFault", Name:="DomainServiceFault", Namespace:="DomainServices")> _
            Function Begin__CanExecuteOperation(ByVal operationName As String, ByVal callback As Global.System.AsyncCallback, ByVal asyncState As Global.System.Object) As Global.System.IAsyncResult
            Function End__CanExecuteOperation(ByVal result As Global.System.IAsyncResult) As Boolean
            
        End Interface
    
        #End Region
    
        Protected Overrides Function CreateEntityImplementation(Of T As Global.Microsoft.LightSwitch.IEntityObject)() As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
            If GetType(T).Equals(GetType(Global.LightSwitchApplication.Cleaner)) Then
                Return New Global.LightSwitchApplication.Implementation.Cleaner()
            End If
            If GetType(T).Equals(GetType(Global.LightSwitchApplication.Client)) Then
                Return New Global.LightSwitchApplication.Implementation.Client()
            End If
            If GetType(T).Equals(GetType(Global.LightSwitchApplication.Job)) Then
                Return New Global.LightSwitchApplication.Implementation.Job()
            End If
            Return Nothing
        End Function
    End Class
    #End Region
    
    #Region "DataServiceImplementationFactory"
    <Global.System.ComponentModel.Composition.PartCreationPolicy(Global.System.ComponentModel.Composition.CreationPolicy.Shared)> _
    <Global.System.ComponentModel.Composition.Export(GetType(Global.Microsoft.LightSwitch.Internal.IDataServiceFactory))> _
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public Class DataServiceFactory
        Inherits Global.Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceFactory
    
        Protected Overrides Function CreateDataService(ByVal dataServiceType As Global.System.Type) As Global.Microsoft.LightSwitch.IDataService
            If dataServiceType.Equals(GetType(Global.LightSwitchApplication.ApplicationData)) Then
                Return New Global.LightSwitchApplication.ApplicationData()
            End If
            Return MyBase.CreateDataService(dataServiceType)
        End Function
    
        Protected Overrides Function CreateDataServiceImplementation(Of TDataService As Global.Microsoft.LightSwitch.IDataService)(ByVal dataService As TDataService) As Global.Microsoft.LightSwitch.Internal.IDataServiceImplementation
            If GetType(TDataService).Equals(GetType(Global.LightSwitchApplication.ApplicationData)) Then
                Return New Global.LightSwitchApplication.Implementation.ApplicationData(dataService)
            End If
            Return MyBase.CreateDataServiceImplementation(dataService)
        End Function
    End Class
    #End Region
    
    <Global.System.ComponentModel.Composition.PartCreationPolicy(Global.System.ComponentModel.Composition.CreationPolicy.Shared)> _
    <Global.System.ComponentModel.Composition.Export(GetType(Global.Microsoft.LightSwitch.Internal.ITypeMappingProvider))> _
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public Class __TypeMapping
        Implements Global.Microsoft.LightSwitch.Internal.ITypeMappingProvider
        Private Function GetImplementationType(ByVal definitionType As Global.System.Type) As Global.System.Type Implements Global.Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType
            If GetType(Global.LightSwitchApplication.Cleaner).Equals(definitionType)
                Return GetType(Global.LightSwitchApplication.Implementation.Cleaner)
            End If
            If GetType(Global.LightSwitchApplication.Client).Equals(definitionType)
                Return GetType(Global.LightSwitchApplication.Implementation.Client)
            End If
            If GetType(Global.LightSwitchApplication.Job).Equals(definitionType)
                Return GetType(Global.LightSwitchApplication.Implementation.Job)
            End If
            Return Nothing
        End Function
    End Class
End Namespace
